feat: support mixed dtype
InfiniTensor/InfiniTensor pull request #102
Opened 2023-07-25 03:42 UTC by bitzyz

| Notice     | 🚧 WORKING IN PROGRESS 🚧
|------------| -
| Based on | `master`

# 支持混合精度模式
1.修改onnx.py中解析onnx node代码，支持对onnx node的拓扑排序（由于混合精度会插入cast节点，但是插入的cast结点放在model.graph.node末尾处，因此会产生部分算子的input查找不到的现象，为避免这一现象需对node结点进行判断，若满足input都存在则创建，否则等后续满足判断条件后再创建）

2023-08-08 09:24 UTC, kilinchange commented on src/operators/matmul.cc
> +        auto shape_ele = std::max(shapeA[i], shapeB[i]);
这里要统一一下命名风格，使用驼峰式，请改成 shapeEle。

2023-08-09 01:03 UTC, YdrMaster requested changes

2023-08-09 01:03 UTC, YdrMaster commented on src/utils/data_convert.cc
> +    Uf32 u;
`Uf32` 可以直接改成：

```c++
union Uf32 {
    float f32;
    uint32_t u32;
    uint16_t u16s[2];
};
```

这样 bf16 直接取 u16s[1] 就行了……只是建议

2023-08-09 01:04 UTC, YdrMaster requested changes

2023-08-09 01:04 UTC, YdrMaster commented on src/operators/element_wise.cc
> +        res[i] = std::max(A_[i], B_[i]);
其实世界上只有两种广播，单向的和双向的。应该把这两种广播做成函数在算子里调……只是建议

2023-08-09 05:16 UTC, kilinchange commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +def _analyse_node(node: NodeProto, tensors):
这个函数加一下返回值类型吧

2023-08-09 08:43 UTC, bitzyz commented on src/operators/matmul.cc
> +        auto shape_ele = std::max(shapeA[i], shapeB[i]);
已修改

2023-08-09 08:43 UTC, bitzyz commented on src/operators/reshape.cc
>  FlattenObj::FlattenObj(GraphObj *graph, Tensor input, Tensor output, int _axis)
已修改

2023-08-09 08:43 UTC, bitzyz commented on src/operators/resize.cc
>      if (axes == std::nullopt)
已修改

2023-08-09 08:43 UTC, bitzyz commented on src/operators/resize.cc
> +    for (size_t i = 0; i < outputs[0]->getRank(); ++i)
已修改

2023-08-09 08:44 UTC, bitzyz commented on src/operators/softmax.cc
>  SoftmaxObj::SoftmaxObj(GraphObj *graph, Tensor input, Tensor output, int _axis)
已修改

2023-08-09 08:45 UTC, bitzyz commented on src/operators/transpose.cc
> +        transposePermute = permute;
这个分支应该是当前输入的permute存在值，只需要额外添加对permute的size检查即可，让其满足
permute.size() == input[0]->getRank()

2023-08-09 08:47 UTC, bitzyz commented on src/utils/data_convert.cc
> +    Uf32 u;
个人觉得差别不大，就先不修改了

2023-08-09 08:47 UTC, bitzyz commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +def _analyse_node(node: NodeProto, tensors):
已填加

2023-08-09 12:48 UTC, kilinchange requested changes

2023-08-10 00:49 UTC, YdrMaster commented on src/operators/unary.cc
> +    case CastType::Float2Float16:
这种东西只要有这么多项，最终还是需要写这么多内容的……其实我不知道这里为什么一定要写成 A(n,2) 个枚举，不能直接存 in out type 就完了么

2023-08-10 01:24 UTC, YdrMaster requested changes

2023-08-10 01:24 UTC, YdrMaster commented on src/operators/transpose.cc
> +        transposePermute = permute;
我的意思是 `permute` 是拷贝到函数的，应该移动到字段（`std::move`）

2023-08-10 08:15 UTC, bitzyz commented on src/operators/unary.cc
> +    case CastType::Float2Float16:
个人觉得这样会很直观，更容易理解代码，且未来用到的cast转换会不会只有几种，因此这一块就先这样，暂不修改吧

2023-08-10 08:15 UTC, bitzyz commented on src/operators/transpose.cc
> +        transposePermute = permute;
已修改

2023-08-10 08:16 UTC, bitzyz commented on src/operators/element_wise.cc
> +        res[i] = std::max(A_[i], B_[i]);
已填加新工具函数在src/utils/operator_utils.cc中

2023-08-10 08:16 UTC, bitzyz commented on pyinfinitensor/tests/test_onnx.py
> +        cast = make_node("Cast", ["input1"], ["output"], to=10, name="cast")
已修改

2023-08-10 08:16 UTC, bitzyz commented on include/operators/unary.h
> +};
已修改

2023-08-10 08:16 UTC, bitzyz commented on src/ffi/ffi_infinitensor.cc
> +    auto cast_output_dtype =
已修改

2023-08-10 08:16 UTC, bitzyz commented on src/operators/softmax.cc
> +    if (_axis >= 0 && (size_t)_axis < input->getRank())
已添加

2023-08-10 08:39 UTC, kilinchange commented on src/core/graph_handler.cc
> +    auto i_type = input->getDType();
这个函数里的 o_type 也改一下吧。

2023-08-10 08:42 UTC, kilinchange commented on src/operators/softmax.cc
> +    if (_axis >= 0 && (size_t)_axis < input->getRank())
这里大括号没有加欸。

2023-08-14 03:18 UTC, YdrMaster approved these changes

2023-08-14 03:31 UTC, kilinchange approved these changes

2023-08-16 13:49 UTC, whjthu approved these changes

2023-08-16 13:49 UTC, merged