impl distributed launch with NCCL
InfiniTensor/InfiniTensor pull request #106
Opened 2023-08-10 09:37 UTC by constroy

1. impl distributed launch with NCCL
2. impl all_reduce, all_gather with NCCL (ops and kernels)
3. impl tensor parallel for resent (experimental)

2023-08-11 02:43 UTC, PanZezhong1725 commented on src/ffi/ffi_infinitensor.cc
> +static Ref<CudaRuntimeObj> cuda_runtime(int deviceId) {
这个我们要不保留一个cuda_runtime()，默认deviceId是0？

2023-08-11 02:46 UTC, PanZezhong1725 commented on .gitmodules
> +	path = examples/NNmodel
这个example目录结构更改可能需要组里说一下

2023-08-11 02:59 UTC, PanZezhong1725 commented on include/core/runtime.h
是否应该加上getWorldSize(), getWorldRank()接口, 并与getDeviceId()加以区分。还可以加一个boolean function通过worldSize是否大于1来判断是否在使用分布式，这样后面直接从runtime调这个function就知道是否需要加通信算子。

2023-08-11 03:14 UTC, constroy commented on include/core/runtime.h
这些接口后面应该会用到，可以用到的时候按需添加。

2023-08-17 05:55 UTC, constroy commented on include/operators/all_gather.h
> +        return {{inputs[0]->getDims()}};
输出形状应该是输入形状的 N 倍，n 是 nccl rank 数。

2023-08-17 06:06 UTC, constroy commented on include/operators/all_gather.h
> +        return {{inputs[0]->getDims()}};
n 需要从 communicator 里面获取

2023-08-18 07:39 UTC, constroy commented on include/cuda/nccl_communicator.h
> +    int getWorldSize() const override {
建议统一省略 `virtual` 的方式，在 `override` 出现时可以省略。

2023-08-18 07:39 UTC, constroy commented on include/cuda/nccl_communicator.h
> +        checkNcclError(ncclCommCount(comm, &world_size));
可以把 rank 等信息存在基类里面，直接获取。因为 NCCL 的 rank 其实也是 communicator 给的，再取回来有些多余。

2023-08-18 07:39 UTC, constroy commented on include/cuda/nccl_communicator.h
> +    virtual int getLocalRank() const override {
local_rank 这个概念其实是上层分布式启动的时候才有的。在runtime里面应该用不到，runtime 直接使用 deviceId。

2023-08-18 07:39 UTC, constroy commented on src/operators/all_gather.cc
> +    // if (!outputs) {
可以删除

2023-08-28 07:11 UTC, bitzyz requested changes

2023-08-28 07:45 UTC, YdrMaster requested changes

2023-08-28 07:45 UTC, YdrMaster commented on include/core/communicator.h
> +    const int worldSize;
真的有必要把这两个写成 const 么……non-static const 成员会导致非常非常多的麻烦，我想如果这个其实具有静态语义最好写成静态的

2023-08-28 07:45 UTC, YdrMaster commented on include/core/runtime.h
> +    std::unique_ptr<CommunicatorObj> comm;
为什么这里需要 `std::unique_ptr`，Runtime 不是已经具有最大生命周期了吗？如果是为了延迟初始化，让子类填写具体类型的话，不要把字段加载基类里，而是在基类里留一个 protected virtual =0 的接口，子类实现父类调用，这样将充分的优化机会让给子类。比如父类只保留 `getCommunicator`，具体如何保存这个对象、如何初始化留给子类。

2023-08-28 07:45 UTC, YdrMaster commented on include/cuda/nccl_communicator.h
> +        const std::string filePath("./" + name + "_nccl_id.bin");
这个直接放相对目录有点吓人啊，不用规划一下（比如弄个文件夹，弄个定位逻辑之类的么）么。不过只是临时用一下好像也没关系。

2023-08-28 07:45 UTC, YdrMaster commented on src/kernels/cuda/all_gather.cc
> +        ncclComm_t comm =
这里有点怪。如果 `context` 已经是 `CudaRuntime` 了，应该能直接从中拿到子类 Commuicator，又何必再从父类拿再转一遍呢？这和 runtime 这些东西的定义是一个问题。

2023-08-29 01:03 UTC, YdrMaster commented on include/core/communicator.h
> +    const int worldSize;
[非常非常麻烦](https://zh.cppreference.com/w/cpp/utility/launder)，不经深思熟虑真的不建议用

2023-08-29 03:25 UTC, constroy commented on src/kernels/cuda/all_gather.cc
> +        ncclComm_t comm =
期望是后面统一成一个 Context，避免在 Context 这一层的 RTTI。现在 Runtime 派生实现的主要是图执行功能，这部分可以单独抽出来。

2023-08-29 03:26 UTC, constroy commented on include/cuda/nccl_communicator.h
> +        const std::string filePath("./" + name + "_nccl_id.bin");
用文件系统做进程间通信，这个是临时的做法。

2023-08-29 03:29 UTC, constroy commented on include/core/runtime.h
> +    std::unique_ptr<CommunicatorObj> comm;
期望是去掉 `Runtime` 这一层的多态，直接统一成一个 `Context`。图执行的功能剥离出去。在 Context 往下再做 device 相关的派生。

2023-08-29 03:35 UTC, constroy commented on include/core/communicator.h
> +    const int worldSize;
可以去掉 `const`

2023-08-29 03:43 UTC, constroy commented on include/core/runtime.h
> +    std::unique_ptr<CommunicatorObj> comm;
先放回到 CudaRuntime 里面

2023-08-30 02:56 UTC, constroy commented on src/kernels/cuda/all_gather.cc
> +        ncclComm_t comm =
这里先保留，因为直接特化成 `NcclCommunicatorObj` 会导致接口不统一，或者会引入很多 NCCL 相关的宏。

2023-08-31 08:22 UTC, bitzyz approved these changes

2023-09-01 01:58 UTC, YdrMaster approved these changes

2023-09-05 01:47 UTC, merged