Xpu abs
InfiniTensor/InfiniTensor pull request #121
Opened 2023-08-25 06:20 UTC by zhangyue207

1. 补充XPU Unary算子: abs, atan, log, cos, sin, tan, sinh, cosh, erf, acos, acosh, asin, asinh，至此，除了round 算子外Unary算子补齐
2. 同样补全CPU上上述算子，主要用来与XPU结果比对
3. 修改了Tensor.cc 中 equalDataImpl中相对误差写死的情况

2023-08-25 07:58 UTC, wanghailu0717 approved these changes

2023-08-25 08:04 UTC, zhangyue207 commented
```
Running tests...
Test project /home/zhangyue/Documents/InfiniTensor/build/Release
      Start  1: test_graph
 1/37 Test  #1: test_graph .......................   Passed    0.02 sec
      Start  2: test_graph_handler
 2/37 Test  #2: test_graph_handler ...............   Passed    0.02 sec
      Start  3: test_graph_replace
 3/37 Test  #3: test_graph_replace ...............   Passed    0.03 sec
      Start  4: test_hash
 4/37 Test  #4: test_hash ........................   Passed    0.02 sec
      Start  5: test_lazy_allocator
 5/37 Test  #5: test_lazy_allocator ..............   Passed    0.02 sec
      Start  6: test_search
 6/37 Test  #6: test_search ......................   Passed    5.02 sec
      Start  7: test_tensor_save
 7/37 Test  #7: test_tensor_save .................   Passed    0.02 sec
      Start  8: test_verify
 8/37 Test  #8: test_verify ......................   Passed    0.02 sec
      Start  9: test_batch_norm
 9/37 Test  #9: test_batch_norm ..................   Passed    0.02 sec
      Start 10: test_clip
10/37 Test #10: test_clip ........................   Passed    0.02 sec
      Start 11: test_concat
11/37 Test #11: test_concat ......................   Passed    0.02 sec
      Start 12: test_conv
12/37 Test #12: test_conv ........................   Passed    0.47 sec
      Start 13: test_conv_transposed_2d
13/37 Test #13: test_conv_transposed_2d ..........   Passed    0.02 sec
      Start 14: test_element_wise
14/37 Test #14: test_element_wise ................   Passed    0.03 sec
      Start 15: test_extend
15/37 Test #15: test_extend ......................   Passed    0.02 sec
      Start 16: test_gather
16/37 Test #16: test_gather ......................   Passed    0.02 sec
      Start 17: test_matmul
17/37 Test #17: test_matmul ......................   Passed    0.02 sec
      Start 18: test_pad
18/37 Test #18: test_pad .........................   Passed    0.02 sec
      Start 19: test_pooling
19/37 Test #19: test_pooling .....................   Passed    0.03 sec
      Start 20: test_reduce_mean
20/37 Test #20: test_reduce_mean .................   Passed    0.02 sec
      Start 21: test_reshape
21/37 Test #21: test_reshape .....................   Passed    0.02 sec
      Start 22: test_resize
22/37 Test #22: test_resize ......................   Passed    0.03 sec
      Start 23: test_slice
23/37 Test #23: test_slice .......................   Passed    0.02 sec
      Start 24: test_split
24/37 Test #24: test_split .......................   Passed    0.02 sec
      Start 25: test_transpose
25/37 Test #25: test_transpose ...................   Passed    0.02 sec
      Start 26: test_xpu_add
26/37 Test #26: test_xpu_add .....................   Passed    0.04 sec
      Start 27: test_xpu_batch_norm
27/37 Test #27: test_xpu_batch_norm ..............   Passed    0.04 sec
      Start 28: test_xpu_concat
28/37 Test #28: test_xpu_concat ..................   Passed    0.03 sec
      Start 29: test_xpu_conv
29/37 Test #29: test_xpu_conv ....................   Passed    0.05 sec
      Start 30: test_xpu_conv_trans
30/37 Test #30: test_xpu_conv_trans ..............   Passed    0.03 sec
      Start 31: test_xpu_element_wise
31/37 Test #31: test_xpu_element_wise ............   Passed    0.03 sec
      Start 32: test_xpu_matmul
32/37 Test #32: test_xpu_matmul ..................   Passed    0.03 sec
      Start 33: test_xpu_pad
33/37 Test #33: test_xpu_pad .....................   Passed    0.05 sec
      Start 34: test_xpu_pooling
34/37 Test #34: test_xpu_pooling .................   Passed    0.03 sec
      Start 35: test_xpu_split
35/37 Test #35: test_xpu_split ...................   Passed    0.03 sec
      Start 36: test_xpu_transpose
36/37 Test #36: test_xpu_transpose ...............   Passed    0.03 sec
      Start 37: test_xpu_unary
37/37 Test #37: test_xpu_unary ...................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 37

Total Test time (real) =   6.44 sec
```

2023-08-28 00:52 UTC, whjthu requested changes

2023-08-28 00:52 UTC, whjthu commented on include/core/op_type.h
>          Atan,               // Binary
这两个也是 unary？既然改了就一起改了吧

2023-08-28 01:36 UTC, zhangyue207 commented on include/core/op_type.h
>          Atan,               // Binary
DONE

2023-08-28 02:14 UTC, Chamberlain0w0 approved these changes

2023-08-28 02:15 UTC, merged