Cuda softmax
InfiniTensor/InfiniTensor pull request #129
Opened 2023-09-05 01:37 UTC by xgqdut2016

add softmax

2023-09-05 03:29 UTC, PanZezhong1725 commented on src/kernels/cuda/softmax.cc
>  class SoftmaxCudnn : public CudaKernelWithoutConfig {
没有使用Cudnn的话，可以把名字改了

2023-09-05 05:30 UTC, wanghailu0717 commented
建议使用统一明晰的风格进行命名

2023-09-05 05:34 UTC, wanghailu0717 commented
另外，建议最好出一个设计实现方案，明确数据的拆分、暂存、流转逻辑。

2023-09-06 00:51 UTC, whjthu requested changes

2023-09-06 00:51 UTC, whjthu commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                            (attr.i for attr in node.attribute if attr.name == "root"),
未修改的内容不要重新格式化

2023-09-06 00:51 UTC, whjthu commented on src/kernels/cuda/softmax.cc
> +        const auto &in_Shape = op->getInputs(0)->getDims(); // input shape
统一使用驼峰命名

2023-09-06 00:51 UTC, whjthu commented on src/kernels/cuda/where.cu
> +                              const int *condition, float *output, int nDims,
这个文件里的非驼峰命名也改掉吧

2023-09-06 00:51 UTC, whjthu commented on test/kernels/cuda/test_cuda_where.cc
> +    test_where(Shape{2, 1, 1, 3}, vector<float>{0, 1, 2, 3, 4, 5}, // inputx
同改下驼峰

2023-09-08 01:58 UTC, PanZezhong1725 approved these changes

2023-09-11 03:28 UTC, xgqdut2016 commented
<img width="1502" alt="new_0" src="https://github.com/InfiniTensor/InfiniTensor/assets/140036308/5b2dc15c-a0ac-4b93-afca-0789c98b6a86">
<img width="1390" alt="new_1" src="https://github.com/InfiniTensor/InfiniTensor/assets/140036308/12f7def4-a6a5-4300-9bee-3fc8e3c771c8">
<img width="1494" alt="old_0" src="https://github.com/InfiniTensor/InfiniTensor/assets/140036308/d9c725d6-6f2d-49f8-9e2c-e047dc4fe981">
<img width="1459" alt="old_1" src="https://github.com/InfiniTensor/InfiniTensor/assets/140036308/cbcd0a4e-e8eb-4b4e-b198-e104ac703f27">

2023-10-30 08:53 UTC, xgqdut2016 commented
![微信截图_20231030165245](https://github.com/InfiniTensor/InfiniTensor/assets/140036308/4d04ff29-d7d8-4bd7-af5b-5b474a813dc2)

2023-11-03 03:14 UTC, xgqdut2016 commented
![Uploading 微信截图_20231103111334.png…]()

2023-11-03 03:25 UTC, xiaonans commented
“调整一下输出格式，让尺寸信息和性能提升信息在一起，方便对比。”
以下是光强调整后的输出：
![微信图片_20231103112315](https://github.com/InfiniTensor/InfiniTensor/assets/51065160/2c5965c2-23a8-4a8b-b66d-b44c1174c334)

2023-11-03 03:29 UTC, xiaonans approved these changes

2023-11-03 05:17 UTC, wanghailu0717 commented on pyinfinitensor/tests/test_onnx.py
> +
这个空行有什么重要的意义吗

2023-11-03 05:17 UTC, whjthu approved these changes

2023-11-03 05:24 UTC, wanghailu0717 commented on src/kernels/cuda/softmax.cc
> +             --i) { // must i = nDims - 1, --i; can't i = 0, i++
（must i = nDims - 1, --i; can't i = 0, i++）为什么？

2023-11-03 05:28 UTC, wanghailu0717 commented on src/kernels/cuda/softmax.cc
> +            size *= inShape[i];
我没有理解错的话，这一段循环是要计算总共有多少个元素，考虑使用已经存在的函数来简化代码
![Uploading image.png…]()

2023-11-03 05:35 UTC, wanghailu0717 commented on src/kernels/cuda/softmax.cu
> +struct __align__(8) MD { // update the global max and sum, store the output at
作为一个开源的项目，建议使用更加文明友好的命名方式，避免不必要的麻烦。

2023-11-03 05:43 UTC, wanghailu0717 commented on src/kernels/cuda/softmax.cu
> +#define max_function(a, b) ((a) > (b) ? (a) : (b))
这里为什么不适用库的函数，有什么特别的原因吗

2023-11-06 00:56 UTC, merged