"modified where"
InfiniTensor/InfiniTensor pull request #131
Opened 2023-09-12 05:52 UTC by xgqdut2016

modified where.cu where.cc cuda_where.h from master

2023-09-13 02:57 UTC, bitzyz requested changes

2023-09-13 02:57 UTC, bitzyz commented on src/kernels/cuda/where.cc
> +        const int xSize = op->getInputs(0)->getDims().size();
这里可以直接使用op->getInputs(0)->getRank()

2023-09-13 02:57 UTC, bitzyz commented on src/kernels/cuda/where.cc
> +        for (int i = nDims - 1; i >= 0; --i) {
是否可以提取一个工具函数，后续我认为满足广播的算子都会用到吧

2023-09-13 08:15 UTC, whjthu requested changes

2023-09-13 08:15 UTC, whjthu commented on include/cuda/cuda_where.h
> +}; // namespace infini
文件结尾空行

2023-09-13 08:15 UTC, whjthu commented on src/kernels/cuda/where.cc
> +        const auto &inputX_Shape = op->getInputs(0)->getDims();
驼峰命名

2023-09-14 02:11 UTC, xgqdut2016 commented on src/kernels/cuda/where.cc
> +        for (int i = nDims - 1; i >= 0; --i) {
已解决，在include/utils/broadcast_shape.h里面

2023-09-14 02:12 UTC, xgqdut2016 commented on src/kernels/cuda/where.cc
> +}; // namespace infini
已解决

2023-09-14 02:40 UTC, whjthu approved these changes

2023-09-14 02:45 UTC, bitzyz approved these changes

2023-09-14 02:45 UTC, merged