Support kvcache
InfiniTensor/InfiniTensor pull request #134
Opened 2023-09-15 02:19 UTC by kilinchange

2023-09-15 05:58 UTC, kilinchange commented
![Uploading image.png…]()
单卡与多卡输出结果对比

2023-09-15 06:01 UTC, kilinchange commented
![image](https://github.com/InfiniTensor/InfiniTensor/assets/44265800/df54ba15-d4a8-4f3e-b9fa-a6b582904151)
单卡与多卡分别跑一轮kvcache(2张静态图)，结果对比如图。

2023-09-15 06:50 UTC, constroy requested changes

2023-09-15 06:50 UTC, constroy commented on examples/distributed/parallel_opt.py
> +        in_plc = place[node.input[1]]
need to check if `in_plc` is `Shard`

2023-09-15 06:50 UTC, constroy commented on examples/distributed/parallel_opt.py
> +    def shard_concat(node: NodeProto, groups: int = 1):
`groups` is not used

2023-09-15 06:54 UTC, xiaonans commented
@kilinchange https://github.com/InfiniTensor/InfiniTensor/pull/127/commits/836226448eac0565b64bd0281ba55ff09815bd4d 这个commit能否帮忙加进pr里？是用来保证多个stub的output和input互相独立的。

2023-09-15 07:26 UTC, kilinchange commented on examples/distributed/parallel_opt.py
> +    def shard_concat(node: NodeProto, groups: int = 1):
fixed

2023-09-18 05:31 UTC, xiaonans approved these changes

2023-09-18 06:03 UTC, PanZezhong1725 approved these changes

2023-09-18 06:17 UTC, merged