Add Gelu operator, ffi, kernel for cpu and gpu.
InfiniTensor/InfiniTensor pull request #148
Opened 2023-10-07 14:04 UTC by KuangjuX

- [x] Gelu Operator
- [x] Gelu ffi 
- [x] Gelu kernel
- [x] Gelu testcase
TODO:
- [ ] Test in CUDA environment

2023-10-08 22:03 UTC, YdrMaster commented
`master` 更新了，需要 merge 或 rebase

2023-10-10 05:45 UTC, whjthu requested changes

2023-10-10 05:45 UTC, whjthu commented on .gitignore
> +.devcontainer
这种非大家通用的文件是不是就不往 .gitignore 里放了？

2023-10-10 05:45 UTC, whjthu commented on src/kernels/cuda/unary.cu
> +
空行删除

2023-10-10 05:51 UTC, YdrMaster approved these changes
重构之后可以改善这种加一个算子要改十几个文件的情况

2023-10-10 07:04 UTC, whjthu approved these changes

2023-10-10 07:21 UTC, merged