Add GatherElements op and cuda kernel
InfiniTensor/InfiniTensor pull request #149
Opened 2023-10-08 06:21 UTC by PanZezhong1725

2023-10-09 03:24 UTC, constroy requested changes

2023-10-09 03:24 UTC, constroy commented on include/cuda/gather.h
> +    printf("%lu\n", sizeof(metaData.indexType));
这个不用保留吧

2023-10-09 03:32 UTC, PanZezhong1725 commented on include/cuda/gather.h
> +    printf("%lu\n", sizeof(metaData.indexType));
忘了删了

2023-10-09 05:13 UTC, constroy approved these changes

2023-10-09 07:25 UTC, zhangyue207 approved these changes

2023-10-09 07:25 UTC, zhangyue207 commented on src/kernels/cuda/gather_elements.cc
> +        auto index = op->getInputs(1);
这里没有用的话是不是删除好一些

2023-10-10 05:54 UTC, whjthu requested changes

2023-10-10 05:54 UTC, whjthu commented on src/operators/gather_elements.cc
> +    auto index_dtype = inputs[1]->getDType();
驼峰

2023-10-10 05:54 UTC, whjthu commented on test/kernels/cuda/test_cuda_gather_elements.cc
> +}
space line

2023-10-10 05:54 UTC, whjthu commented on src/kernels/cuda/gather_elements.cu
> +        IT_TODO_HALT_MSG("GatherElements Cuda Kernel: Unsupported type.\n");
Unsupported data type?

2023-10-10 05:54 UTC, whjthu commented on src/kernels/cuda/gather_elements.cc
> +
多余空行

2023-10-12 01:12 UTC, whjthu approved these changes

2023-10-12 01:18 UTC, merged