Add ReduceSum op and kernel
InfiniTensor/InfiniTensor pull request #160
Opened 2023-10-13 07:38 UTC by PanZezhong1725

复用ReduceMean的代码，将两者作为ReduceBase的子类，修改了部分文件名。

2023-10-31 05:56 UTC, Chamberlain0w0 approved these changes

2023-10-31 06:21 UTC, zhangyue207 requested changes

2023-10-31 06:21 UTC, zhangyue207 commented on src/core/graph_handler.cc
> +                ->addOp<obj##Obj>(std::move(data), reduced, axes, keepdims)    \
好像有个宏连接的操作 _CAT(A, B)，感觉复用之前的会好一些

2023-10-31 06:21 UTC, zhangyue207 commented on include/operators/reduce.h
>       * @param graph The computation graph that this operator belongs to.
少了参数 OpType的解释

2023-10-31 06:21 UTC, zhangyue207 commented on src/kernels/cuda/reduce.cc
> +    cudnnReduceTensorOp_t getReduceOp() const override {
我看这个函数有些地方命名时getRedOp() 有没有一个统一的命名方式

2023-10-31 06:27 UTC, Chamberlain0w0 commented on src/kernels/cuda/reduce.cc
> +    cudnnReduceTensorOp_t getReduceOp() const override {
AllReduce通信算子那边用的是getRedOp

2023-11-01 02:26 UTC, PanZezhong1725 commented on src/kernels/cuda/reduce.cc
> +    cudnnReduceTensorOp_t getReduceOp() const override {
这个我觉得没必要对齐，这个函数只在reduceCudnnBase的内部用。

2023-11-23 05:11 UTC, zhangyue207 approved these changes

2023-11-24 01:25 UTC, whjthu approved these changes

2023-11-24 01:29 UTC, merged