support ascend
InfiniTensor/InfiniTensor pull request #165
Opened 2023-10-20 06:56 UTC by wanghailu0717

2024-05-15 06:35 UTC, zhangyue207 requested changes

2024-05-15 06:35 UTC, zhangyue207 commented on include/operators/instance_norm.h
> +class InstanceNormObj : public OperatorObj {
建议私有变量还是显示生命private 好一些

2024-05-15 06:35 UTC, zhangyue207 commented on include/operators/unary.h
> +class LeakyReluObj : public OperatorObj {
这里也是

2024-06-11 02:56 UTC, OdinaryWord commented on env.sh
> +# 配置华为ASCEND NPU 的 HOME 路径，请注意 /usr/local/ascend 是昆仑芯软件栈提供的软件包路径。
已修改

2024-06-11 03:01 UTC, OdinaryWord commented on include/operators/instance_norm.h
> +class InstanceNormObj : public OperatorObj {
已修改

2024-06-11 03:01 UTC, OdinaryWord commented on include/operators/unary.h
> +class LeakyReluObj : public OperatorObj {
已修改

2024-06-11 03:04 UTC, OdinaryWord commented on CMakeLists.txt
> +endif()
已修改

2024-06-13 03:19 UTC, zhangyue207 approved these changes

2024-06-26 02:53 UTC, xgqdut2016 approved these changes

2024-07-03 03:28 UTC, OdinaryWord commented on include/ascend/hccl_communicator.h
> +        // assert(ret == HCCL_SUCCESS);
已经加回，构建aclruntime的时候使用默认context，否则HcclCommDestroy会报错。

2024-07-05 06:39 UTC, whjthu requested changes

2024-07-08 07:41 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +    do {                                                                       \
这里是模仿的昇腾示例的写法，宏定义的目的是做返回值的检查。代码只会执行一次，用do while（0）的意义是防止宏展开后的代码对周围代码产生影响。

2024-07-08 08:39 UTC, OdinaryWord commented on src/kernels/ascend/element_wise.cc
> +}; // namespace infini
已删除

2024-08-02 06:08 UTC, OdinaryWord commented on CMakeLists.txt
> +    set(ASCEND_HOME ${ASCEND_HOME} CACHE STRING "ASCEND_HOME directory for Kunlun development")
Kunlun

2024-08-02 06:08 UTC, OdinaryWord commented on CMakeLists.txt
> +    set(ASCEND_HOME $ENV{ASCEND_HOME} CACHE STRING "ASCEND_HOME directory for Kunlun development")
Kunlun

2024-08-02 06:24 UTC, OdinaryWord commented on include/ascend/ascend_common.h
> +#include "core/common.h"
看下是不是没用到

2024-08-02 06:26 UTC, OdinaryWord commented on include/ascend/ascend_kernel_without_config.h
> +    std::vector<int64_t> castTo64(std::vector<int> const &v32) const {
放在core/common.h里

2024-08-02 06:27 UTC, OdinaryWord commented on include/ascend/ascend_kernel_without_config.h
> +    Shape getStride(std::vector<int> Dim) const {
这里tensor里有get_stride，是不是重复了。

2024-08-02 06:35 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +    } while (0)
这俩没用到，是不是可以删了

2024-08-02 06:40 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        CHECK_RET(ret == ACL_SUCCESS,
统一改成这种

2024-08-02 06:45 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        workspaceSize = 3ll << 33; // 3 GB
3ll * (1 << 30)

2024-08-02 06:48 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        // ret = aclrtCreateContext(&context, deviceId);
删掉

2024-08-02 06:49 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        // aclrtDestroyContext(context);
删

2024-08-02 06:52 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +    // double runEvaluation(const Graph &graph, int nWarmups,
删

2024-08-02 06:53 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        checkASCENDError(
改成checkRet

2024-08-02 06:56 UTC, OdinaryWord commented on include/ascend/hccl_communicator.h
> +        // 在 rootRank 获取 rootInfo
改成英文

2024-08-02 07:12 UTC, OdinaryWord commented on include/operators/resize.h
> +        return inputs[1]->getDType() == DataType::Int64;
下来研究一下

2024-08-02 07:33 UTC, OdinaryWord commented on src/kernels/ascend/all_gather.cc
> +        // void *output = op->getOutput()->getRawDataPtr<void *>();
删

2024-08-02 07:34 UTC, OdinaryWord commented on src/kernels/ascend/all_gather.cc
> +        // void *output = op->getOutput()->getRawDataPtr<void *>();
删

2024-08-02 07:37 UTC, OdinaryWord commented on src/kernels/ascend/all_reduce.cc
> +        // TODO: Using default stream 0 for now.
删

2024-08-02 07:39 UTC, OdinaryWord commented on src/kernels/ascend/batch_norm.cc
> +        // auto tmp_err_msg = aclGetRecentErrMsg();
写道ascend_common.h里。

2024-08-02 07:43 UTC, OdinaryWord commented on src/kernels/ascend/batch_norm.cc
> +        // aclDestroyTensor(inputTensor);
恢复

2024-08-02 07:53 UTC, OdinaryWord commented on src/kernels/ascend/conv.cc
> +        // std::vector<int64_t> ksize = {r, s};
删

2024-08-02 07:56 UTC, OdinaryWord commented on src/kernels/ascend/gather.cc
> +            // op->getInputs(1)->getDType() == DataType::Int32 ? ACL_INT32
删

2024-08-02 08:00 UTC, OdinaryWord commented on src/kernels/ascend/pad2d.cc
> +        ret = aclnnReflectionPad2d(workspaceAddr, workspaceSize, executor,
cherry pick zyz

2024-08-02 08:01 UTC, OdinaryWord commented on src/kernels/ascend/recv.cc
> +        // printf("###rank:%u,source:%d,outputCount:%d,destination:%d\n", rank,
删

2024-08-02 08:04 UTC, OdinaryWord commented on src/kernels/ascend/send.cc
> +        // printf("***rank:%u,source:%d,inputCount:%d,destination:%d\n", rank,
删

2024-08-02 08:05 UTC, OdinaryWord commented on src/kernels/ascend/send.cc
> +        IT_ASSERT(op->getDType() == DataType::Float32);
其他算子加一下

2024-08-02 08:08 UTC, OdinaryWord commented on src/operators/unary.cc
> +    os << "alpha=" << alphaValue << ")";
删

2024-08-05 06:43 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +#define LOG_PRINT(message, ...)                                                \
已删除CHECK_RET 和 LOG_PRINT，用checkASCENDError替代。

2024-08-05 06:45 UTC, OdinaryWord commented on include/ascend/hccl_communicator.h
> +#define ACLCHECK(ret)                                                          \
已删除，用checkASCENDError替代。

2024-08-05 06:49 UTC, OdinaryWord commented on include/ascend/hccl_communicator.h
> +        assert(ret == HCCL_SUCCESS);
已修改为使用checkHCCLError。

2024-08-05 07:29 UTC, OdinaryWord commented on src/kernels/ascend/batch_norm.cc
> +        assert(ret == ACL_SUCCESS);
已改为用checkASCENDError替代，并修改判断位置。

2024-08-05 08:54 UTC, OdinaryWord commented on src/kernels/ascend/conv.cc
> +        // aclDestroyTensor(inputTensor);
取消了所有aclDestroyTensor的注释，没有的添加了aclDestroyTensor。

2024-08-05 09:48 UTC, OdinaryWord commented on src/kernels/ascend/element_wise.cc
> +}; // namespace infini
均已删除

2024-08-06 02:07 UTC, OdinaryWord commented on CMakeLists.txt
> +    set(ASCEND_HOME ${ASCEND_HOME} CACHE STRING "ASCEND_HOME directory for Kunlun development")
已修改

2024-08-06 02:07 UTC, OdinaryWord commented on CMakeLists.txt
> +    set(ASCEND_HOME $ENV{ASCEND_HOME} CACHE STRING "ASCEND_HOME directory for Kunlun development")
已修改

2024-08-06 07:19 UTC, OdinaryWord commented on include/ascend/ascend_kernel_without_config.h
> +    std::vector<int64_t> castTo64(std::vector<int> const &v32) const {
已迁移至core/common.h

2024-08-06 07:20 UTC, OdinaryWord commented on include/ascend/ascend_kernel_without_config.h
> +    Shape getStride(std::vector<int> Dim) const {
这里不是对tensor的getstride，但是只有一个地方用到，已删除并迁移至DepthToSpaceAclnn内作为一个匿名函数。

2024-08-06 07:22 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +    } while (0)
已删除LOG_PRINT，用checkASCENDError替代

2024-08-06 07:24 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        CHECK_RET(ret == ACL_SUCCESS,
统一使用checkASCENDError

2024-08-06 07:25 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        workspaceSize = 3ll << 33; // 3 GB
已修改

2024-08-06 07:40 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        // ret = aclrtCreateContext(&context, deviceId);
已删除

2024-08-06 07:40 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        // aclrtDestroyContext(context);
已删除

2024-08-06 07:41 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +    // double runEvaluation(const Graph &graph, int nWarmups,
已删除

2024-08-06 07:41 UTC, OdinaryWord commented on include/ascend/ascend_runtime.h
> +        checkASCENDError(
统一使用了checkASCENDError

2024-08-06 07:43 UTC, OdinaryWord commented on include/ascend/hccl_communicator.h
> +        // 在 rootRank 获取 rootInfo
已修改

2024-08-06 07:44 UTC, OdinaryWord commented on src/kernels/ascend/all_gather.cc
> +        // void *output = op->getOutput()->getRawDataPtr<void *>();
已删除

2024-08-06 07:45 UTC, OdinaryWord commented on src/kernels/ascend/all_gather.cc
> +        // void *output = op->getOutput()->getRawDataPtr<void *>();
已删除

2024-08-06 07:45 UTC, OdinaryWord commented on src/kernels/ascend/all_reduce.cc
> +        // HcclDataType
已删除

2024-08-06 07:46 UTC, OdinaryWord commented on src/kernels/ascend/all_reduce.cc
> +        // TODO: Using default stream 0 for now.
已删

2024-08-06 08:01 UTC, OdinaryWord commented on src/kernels/ascend/batch_norm.cc
> +        // auto tmp_err_msg = aclGetRecentErrMsg();
已在ascend_common.h添加GetRecentErrMsg宏定义

2024-08-06 08:02 UTC, OdinaryWord commented on src/kernels/ascend/batch_norm.cc
> +        // aclDestroyTensor(inputTensor);
均已恢复

2024-08-06 08:06 UTC, OdinaryWord commented on src/kernels/ascend/conv.cc
> +        // std::vector<int64_t> ksize = {r, s};
没用到的注释代码均已删除

2024-08-06 08:06 UTC, OdinaryWord commented on src/kernels/ascend/gather.cc
> +            // op->getInputs(1)->getDType() == DataType::Int32 ? ACL_INT32
已删

2024-08-06 08:06 UTC, OdinaryWord commented on src/kernels/ascend/recv.cc
> +        // printf("###rank:%u,source:%d,outputCount:%d,destination:%d\n", rank,
已删

2024-08-06 08:07 UTC, OdinaryWord commented on src/kernels/ascend/send.cc
> +        // printf("***rank:%u,source:%d,inputCount:%d,destination:%d\n", rank,
已删

2024-08-06 08:13 UTC, OdinaryWord commented on src/kernels/ascend/send.cc
> +        IT_ASSERT(op->getDType() == DataType::Float32);
均已添加

2024-08-06 09:18 UTC, OdinaryWord commented on src/kernels/ascend/pad2d.cc
> +        ret = aclnnReflectionPad2d(workspaceAddr, workspaceSize, executor,
已替换为aclnnConstantPadNd，并且添加单算子测试，测试通过。

2024-08-08 08:16 UTC, OdinaryWord commented on include/operators/resize.h
> +        return inputs[1]->getDType() == DataType::Int64;
基于sizes和scales只能有一个有值的原则，添加isGivenSizes参数，在init时对该参数赋值。

2024-08-15 02:10 UTC, kilinchange commented on src/kernels/ascend/pad2d.cc
> +}; // namespace infini
分号没删

2024-08-15 02:13 UTC, kilinchange commented on test/kernels/ascend/test_ascend_element_wise.cc
> +    // testElementWise<MulObj>(IncrementalGenerator(),
这个测试函数为什么要注释掉其余的 elementwise kernel 的 test 呢？

2024-08-15 02:14 UTC, kilinchange commented on test/kernels/ascend/test_ascend_gather.cc
> +    //}
上面的注释还需要吗？不需要的话就删了吧

2024-08-15 02:15 UTC, kilinchange commented on test/kernels/ascend/test_ascend_gather.cc
> +    //}
这里的注释也是，确认一下，不需要的话就删了吧

2024-08-15 02:17 UTC, kilinchange commented on test/kernels/ascend/test_ascend_layernorm.cc
> +
这里也是，确认下为什么要注释掉

2024-08-15 02:18 UTC, kilinchange commented on test/kernels/ascend/test_ascend_resize.cc
> +// }
这里也是，确认注释

2024-08-15 02:18 UTC, kilinchange commented on test/kernels/ascend/test_ascend_sendrecv.cc
> +} // namespace infini
注释

2024-08-15 02:19 UTC, kilinchange commented on test/kernels/ascend/test_ascend_unary.cc
> +    // testUnary<RoundObj>(IncrementalGenerator(), Shape{1, 2, 2, 3});
这里为什么要注释掉个别 kernel 的 test？

2024-08-15 02:27 UTC, kilinchange commented
test_cuda_resize 这个测例在 cuda 上无法通过，可能是因为 pr 里改了 resize 参数的数据类型，麻烦更新一下 cuda 那边 test 里的测例。

2024-08-15 03:10 UTC, kilinchange commented
![img_v3_02dp_881bd5e1-52de-4e40-b345-ac95639d592g](https://github.com/user-attachments/assets/76d8c4e4-5867-44df-982f-ef75dce2ec9e)
寒武纪 370 机器测试通过

2024-08-15 09:29 UTC, OdinaryWord commented on src/kernels/ascend/pad2d.cc
> +}; // namespace infini
已删

2024-08-15 09:34 UTC, OdinaryWord commented
<img width="467" alt="微信图片_20240815173347" src="https://github.com/user-attachments/assets/592e81a5-00ab-4a7b-a9e8-8e264f20abbb">
NVIDIA A100 机器测试通过

2024-08-16 08:39 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_element_wise.cc
> +    // testElementWise<MulObj>(IncrementalGenerator(),
已取消注释并测试通过。

2024-08-16 08:52 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_gather.cc
> +    //}
已删

2024-08-16 08:53 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_layernorm.cc
> +
这部分保留，取消注释并通过测试。

2024-08-16 08:53 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_gather.cc
> +    //}
这部分保留，取消注释并通过测试。

2024-08-16 08:55 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_layernorm.cc
> +
已修改并通过测试，scales暂不支持broadcast

2024-08-16 08:59 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_resize.cc
> +// }
已修改并通过测试。

2024-08-16 09:02 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_sendrecv.cc
> +} // namespace infini
已删除

2024-08-16 09:34 UTC, OdinaryWord commented on test/kernels/ascend/test_ascend_unary.cc
> +    // testUnary<RoundObj>(IncrementalGenerator(), Shape{1, 2, 2, 3});
已修改，原来的test需要和cpu对比，注释掉的几个没有cpu实现。现在改为和ExpectData对比，并测试通过。

2024-08-16 09:43 UTC, OdinaryWord commented
<img width="437" alt="微信图片_20240816174320" src="https://github.com/user-attachments/assets/9f15c67a-fa71-4686-aad4-dff51d776f52">
ascend 910B3 机器测试通过

2024-08-19 02:26 UTC, kilinchange approved these changes

2024-08-20 14:09 UTC, whjthu approved these changes

2024-08-20 14:09 UTC, merged