XCCL support
InfiniTensor/InfiniTensor pull request #171
Opened 2023-10-30 02:37 UTC by zhangyue207

1. Add findXCCL.cmake to find xccl lib and headers
2. Add XCCL allreduce

2023-10-30 03:15 UTC, zhangyue207 commented
![image](https://github.com/InfiniTensor/InfiniTensor/assets/138768300/a23bf28a-fc0c-40b2-9cb4-0197449e325b)
通过单测，但是需要在Makefile中手动设置编译器，因为.210 昆仑server上默认gcc版本落后了

2023-10-30 06:53 UTC, constroy requested changes

2023-10-30 06:53 UTC, constroy commented on src/kernels/kunlun/all_reduce.cc
> +        xpu_wait(0);
为什么需要 wait，我们的框架里 kernel 本身应该是不做同步的？

2023-10-30 06:53 UTC, constroy commented on Makefile
> +	cd build/$(TYPE) && cmake $(CMAKE_OPT) ../.. && make -j32
这个增加是为什么？

2023-10-30 06:53 UTC, constroy commented on src/kernels/kunlun/all_reduce.cc
> +
Average 是不是也可以加上？

2023-10-30 06:58 UTC, zhangyue207 commented on Makefile
> +	cd build/$(TYPE) && cmake $(CMAKE_OPT) ../.. && make -j32
可以编得更快一些。。。忘记改回去了

2023-10-30 06:59 UTC, zhangyue207 commented on src/kernels/kunlun/all_reduce.cc
> +
目前是没有avg，可以在compute函数里改

2023-10-30 06:59 UTC, zhangyue207 commented on src/kernels/kunlun/all_reduce.cc
> +
xccl目前只支持了 add min max三个reduce操作

2023-10-30 07:01 UTC, zhangyue207 commented on src/kernels/kunlun/all_reduce.cc
> +        xpu_wait(0);
我不太了解
![image](https://github.com/InfiniTensor/InfiniTensor/assets/138768300/3c47f38d-e78e-465b-a7f6-981cd4a519a0)
![image](https://github.com/InfiniTensor/InfiniTensor/assets/138768300/10638849-5aa6-4fc3-88d0-8e4604d82ac7)

2023-10-30 07:02 UTC, zhangyue207 commented on src/kernels/kunlun/all_reduce.cc
> +        xpu_wait(0);
nccl 的 allreduce 也是异步么

2023-10-30 07:19 UTC, zhangyue207 commented on src/kernels/kunlun/all_reduce.cc
> +        xpu_wait(0);
已修改

2023-10-30 07:20 UTC, zhangyue207 commented on Makefile
> +	cd build/$(TYPE) && cmake $(CMAKE_OPT) ../.. && make -j32
已改回

2023-10-30 08:06 UTC, constroy commented on src/kernels/kunlun/all_reduce.cc
> +
那先不加别的吧。

2023-10-30 08:09 UTC, constroy commented on src/kernels/kunlun/all_reduce.cc
> +        xpu_wait(0);
算子内应该不用做同步，算子跑在同一个 stream 就能保证顺序。

2024-01-11 03:29 UTC, zhangyue207 commented
![image](https://github.com/InfiniTensor/InfiniTensor/assets/138768300/89c5c3bd-ad3c-493b-ac29-9ac79441bd36)

2024-01-11 03:37 UTC, zhangyue207 commented
![image](https://github.com/InfiniTensor/InfiniTensor/assets/138768300/b41b3c5f-039f-4acc-af83-f3ca9326551b)
GPT2 单卡结果与onnxruntime对比

2024-01-11 03:40 UTC, zhangyue207 commented
![image](https://github.com/InfiniTensor/InfiniTensor/assets/138768300/6be2870d-4566-41df-a0e8-f2da2277c1e2)

python3 launch_kunlun.py --nproc_per_node=2 --model gpt2/gpt2_bs16.onnx --batch_size 16 --length 1024 

分布式结果和单卡结果对比

2024-02-21 06:08 UTC, wanghailu0717 approved these changes

2024-02-21 07:02 UTC, xiaonans approved these changes

2024-02-23 06:09 UTC, whjthu requested changes

2024-02-23 06:09 UTC, whjthu commented on test/kernels/kunlun/test_kunlun_softmax.cc
> +    outputKunlun2Cpu->printData();
这个应该删掉或注释掉吧

2024-02-23 06:09 UTC, whjthu commented on test/kunlun/test_kunlun_workspace.cc
> +} // namespace infini
补充文件结尾空行

2024-02-23 06:09 UTC, whjthu commented on test/kernels/kunlun/test_kunlun_matmul.cc
> +}; // namespace infini
没有分号

2024-02-27 05:28 UTC, zhangyue207 commented on include/kunlun/kunlun_runtime.h
> +        size_t workspaceSize = 3ll << 30; // 3 GB
这个值跟之前设置的一样没有改动

2024-02-27 05:33 UTC, zhangyue207 commented on include/operators/unary.h
> +    Float2Float,
之前遇到过一个float2float转换的cast没有被消掉，为了避免报错就加了这个

2024-02-27 05:35 UTC, zhangyue207 commented on src/kernels/kunlun/gather.cc
> +        Shape aShape = op->getInputs(0)->getDims();
不会，是因为我比较倾向把类型显示写出来

2024-02-27 05:35 UTC, zhangyue207 commented on src/kernels/kunlun/gather.cc
> +        Shape aShape = op->getInputs(0)->getDims();
那我把写法统一把

2024-02-27 06:01 UTC, zhangyue207 commented
修改后结果无变动：
![image](https://github.com/InfiniTensor/InfiniTensor/assets/138768300/56e2c2b4-7c74-4816-9eb9-94b273bd3d26)

2024-02-28 03:00 UTC, whjthu requested changes

2024-02-29 03:48 UTC, merged