support Dynamic tensor infer shape and fix memory pool
InfiniTensor/InfiniTensor pull request #176
Opened 2023-11-01 02:33 UTC by bitzyz

1. 支持用户在前端通过设置set_input( List(input shape) )来动态推理每次图的形状
   a. 添加动态推理形状逻辑的相关功能函数
   b. 修改算子的infershape函数，解除const限制
   c. 修改reshape算子与onnx对齐，支持部分算子(matmul等)动态更改内部参数
2. 适配kv cache相关工作
   a. 添加kv cache跑分布式的一个example
   b. 为分配器添加了一个简单的内存池
   c. 支持concat在两个输入的情况下，有一方为0时退化为identity算子，将kv cache的两张图合并为一张

2023-11-15 02:42 UTC, YdrMaster approved these changes

2023-11-15 02:44 UTC, kilinchange commented on examples/distributed/launch_kvcache_change_seq_len.py
> +import argparse
这个脚本不需要合入 master，我直接删了。

2023-11-15 02:56 UTC, kilinchange approved these changes

2023-11-21 17:23 UTC, whjthu requested changes

2023-11-21 17:23 UTC, whjthu commented on include/core/graph.h
> +    Tensor getTensorWithUid(int fuid) const;
看实现，这个应该是叫 getTensorByUid？

2023-11-21 17:23 UTC, whjthu commented on include/core/graph.h
> +    Tensor getTensorWithUid(int fuid) const;
甚至是不是直接叫 getTensor(int uid) 就可以了，从接口应该就能看出功能了

2023-11-21 17:23 UTC, whjthu commented on include/core/tensor.h
> +    void setSize(size_t size) { _size = size; }
setSize 应该是在 setShape 时一起做了？ size 与 shape 对不上这种情况应该是不合法的，不能出现这种中间状态吧？

2023-11-21 17:23 UTC, whjthu commented on include/operators/conv.h
> +    void setNCHWFRS(Tensor input, Tensor weight);
这个 set 也应该是在更新了形状信息的时候一起做的吧？比如调 inferShape 的时候？这几个参数与 input 和 weight 的状态不一样也应该是不合法的中间状态，不能出现

2023-11-21 17:23 UTC, whjthu commented on include/operators/reshape.h
> +    Shape outputShape;
outputShape 与 dims 在什么情况下会不相同？

2023-11-21 17:23 UTC, whjthu commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +    def getShape(self, name: str) -> List[int]:
这个函数好像一模一样的出现了两次？

2023-11-21 17:23 UTC, whjthu commented on src/kernels/cuda/element_wise.cu
> +        ((float *)z)[i] =
既然都写成这样了。。是不是可以搞成模板类了

2023-11-21 17:23 UTC, whjthu commented on src/kernels/cuda/split_concat.cc
> +    void do_compute1(const Operator &op, size_t index) const {
改个比较有意义的名字吧，而且这个函数好像就是实现了一个 copy ？如果只有下面一处调用不需要单独搞个函数出来吧

2023-11-21 17:23 UTC, whjthu commented on src/kernels/cuda/split_concat.cc
> +    void do_compute1(const Operator &op, size_t index) const {
而且这里好像是可以做 inplace 优化的？类似于 reshape 和 copy 之类的函数

2023-11-21 17:23 UTC, whjthu commented on src/operators/concat.cc
> +    if (inputs.size() == 2) {
为什么只有 inputs.size() == 2 时会有这种情况出现？这个是特例还是某种特性？

2023-11-21 17:23 UTC, whjthu commented on src/operators/conv.cc
> +    setNCHWFRS(input, weight);
这个函数好像也是用到的地方比较少，而且与 setAuxilaryAttributes 重合度极高，可以要确认下这两个接口怎么保留

2023-11-21 17:23 UTC, whjthu commented on src/operators/conv.cc
> +    n = input->getDims()[0];
这里就又没有 setNCHWFRS 接口了

2023-11-22 09:24 UTC, bitzyz commented on src/operators/concat.cc
> +    if (inputs.size() == 2) {
适配kvcache将两图合并时，concat输入为两个，但是第一次执行的时候会有一个输入为空tensor，所以这里做了个特殊处理，没有考虑很泛化的情况

2023-11-22 09:24 UTC, bitzyz commented on include/core/graph.h
> +    Tensor getTensorWithUid(int fuid) const;
已修改

2023-11-22 09:25 UTC, bitzyz commented on include/core/tensor.h
> +    void setSize(size_t size) { _size = size; }
已删除setSize函数

2023-11-22 09:26 UTC, bitzyz commented on include/operators/conv.h
> +    void setNCHWFRS(Tensor input, Tensor weight);
这个本身调用就是在infershape里调用，当时只是想抽出来做个函数，现已删除

2023-11-22 09:27 UTC, bitzyz commented on include/operators/reshape.h
> +    Shape outputShape;
dims是传入的shape如[-1, 0]，outputShape是实际计算推理得出的形状

2023-11-22 09:27 UTC, bitzyz commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +    def getShape(self, name: str) -> List[int]:
已删除

2023-11-22 09:28 UTC, bitzyz commented on src/operators/conv.cc
> +    setNCHWFRS(input, weight);
已删除setNCHWFRS接口，当时没注意到setAuxilaryAttributes这个函数，确实重合度挺高的.......

2023-11-22 09:29 UTC, bitzyz commented on src/operators/conv.cc
> +    n = input->getDims()[0];
这里是因为有个trans，所以实际执行和setNCHWFRS不一样，所以没调

2023-11-23 03:44 UTC, bitzyz commented on src/kernels/cuda/element_wise.cu
> +        ((float *)z)[i] =
已修改

2023-11-23 03:44 UTC, bitzyz commented on src/kernels/cuda/split_concat.cc
> +    void do_compute1(const Operator &op, size_t index) const {
已修改

2023-11-23 05:11 UTC, whjthu approved these changes

2023-11-23 05:11 UTC, merged