Add layer normalization
InfiniTensor/InfiniTensor pull request #181
Opened 2023-11-14 07:47 UTC by xgqdut2016

the baseline of layernorm

2023-11-15 02:54 UTC, OdinaryWord approved these changes

2023-11-15 06:14 UTC, bitzyz requested changes

2023-11-15 06:14 UTC, bitzyz commented on src/kernels/cuda/layer_norm.cu
> +        __shared__ float sigma2_total[BLOCK_DIM_y];
命名规范性

2023-11-15 08:31 UTC, kilinchange commented on src/kernels/cuda/layer_norm.cc
> +        void *const biasData = (op->getInputs(2)->getRawDataPtr<void *>());
@xgqdut2016

2023-11-15 08:37 UTC, kilinchange commented on src/operators/layer_norm.cc
> +      eps(eps), axis(axis), stash_type(stash_type) {
fixed

2023-11-15 08:38 UTC, kilinchange commented on src/operators/layer_norm.cc
> +LayerNormObj::inferShape(const TensorVec &inputs) const {
fixed

2023-11-17 06:11 UTC, xgqdut2016 commented on src/kernels/cuda/layer_norm.cc
> +        void *const biasData = (op->getInputs(2)->getRawDataPtr<void *>());
> 这里同样需要考虑bias不存在的情况

已经解决

2023-11-17 06:11 UTC, xgqdut2016 commented on src/kernels/cuda/layer_norm.cu
> +        __shared__ float sigma2_total[BLOCK_DIM_y];
> 命名规范性

已经修改命名

2023-11-20 01:52 UTC, bitzyz approved these changes

2023-11-21 16:59 UTC, whjthu requested changes

2023-11-21 16:59 UTC, whjthu commented on include/cuda/cuda_layernorm.h
> +void hasLaynormKernel(const float *input, const float *scale, const float eps,
这个 has 的意思是有没有 bias 吗？如果是参数列表不一样，是不是直接搞个重载就行了？而且这个名字也太奇怪了==

2023-11-22 02:03 UTC, xgqdut2016 commented on include/cuda/cuda_layernorm.h
> +void hasLaynormKernel(const float *input, const float *scale, const float eps,
已经修复，现在支持重载来接收optional参数

2023-11-22 02:03 UTC, xgqdut2016 commented on include/cuda/cuda_layernorm.h
> +void hasLaynormKernel(const float *input, const float *scale, const float eps,
> 这个 has 的意思是有没有 bias 吗？如果是参数列表不一样，是不是直接搞个重载就行了？而且这个名字也太奇怪了==

已经修复，现在支持重载来支持optional参数

2023-11-24 01:29 UTC, whjthu approved these changes

2023-11-24 07:15 UTC, merged