baseline sendrecv, bug
InfiniTensor/InfiniTensor pull request #182
Opened 2023-11-21 09:33 UTC by xgqdut2016

InfiniTensor point to point, sendrecv

2023-12-07 06:13 UTC, PanZezhong1725 requested changes

2023-12-07 06:13 UTC, PanZezhong1725 commented on test/kernels/cuda/test_cuda_sendrecv.cc
> +    vector<float> data = {2., 3., 5., 6.};
没必要传两个一模一样的vector

2023-12-08 01:51 UTC, xgqdut2016 commented on src/kernels/cuda/recv.cc
> +        IT_ASSERT(op->getDType() == DataType::Float32);
> 为什么只允许float32？

这是当时抄写broadcast遗留下来的，我看了一下，这几个NCCL相关的算子都有这个判断，应该都可以删掉这个限制

2023-12-08 02:19 UTC, xgqdut2016 commented on include/core/graph_handler.h
> +    Tensor send(Tensor input, int source, int destination, Shape dims,
> send应该不需要dims，input里有形状信息

OK，已经删除send里面的dim参数

2023-12-14 08:33 UTC, zhengly123 approved these changes

2023-12-14 08:38 UTC, merged