- modify error info when kernel not found
InfiniTensor/InfiniTensor pull request #191
Opened 2023-12-01 07:14 UTC by kilinchange

修改后报错信息示例：
![image](https://github.com/InfiniTensor/InfiniTensor/assets/44265800/948da54a-40c0-474a-b5ae-23f49eda526e)

2023-12-07 07:46 UTC, whjthu requested changes

2023-12-07 07:46 UTC, whjthu commented on src/utils/operator_utils.cc
> +        deviceStr = "UNKNOWN_DEVICE";
建议是不是直接 assert 掉，出现我们没有定义的硬件应该是未定义行为，不应该再继续执行。另外建议是不是可以把 device to string 单独作一个函数？感觉其他地方应该也会用，而且好像是有些地方已经使用了类似功能的

2023-12-11 02:45 UTC, kilinchange commented on src/utils/operator_utils.cc
> +        deviceStr = "UNKNOWN_DEVICE";
已修改。

2023-12-26 05:21 UTC, bitzyz approved these changes

2023-12-27 01:43 UTC, whjthu approved these changes

2023-12-27 01:43 UTC, merged