[WIP] add frontend resize kernel
InfiniTensor/InfiniTensor pull request #194
Opened 2023-12-08 09:50 UTC by kilinchange

前端补齐 resize kernel

2023-12-27 02:27 UTC, bitzyz requested changes

2023-12-27 02:27 UTC, bitzyz commented on src/core/graph_handler.cc
> +    }
为什么不直接将tensor传进来，而要在这里单独做一次dataMalloc，会不会导致多次malloc的现象

2023-12-27 02:53 UTC, kilinchange commented on src/core/graph_handler.cc
> +    }
因为前端是在构图完成后再进行 dataMalloc，然后往 input tensor 里传值。但是 resize 这个算子在构造时就需要这几个 input 里有值才能完成各种初始化操作，所以就只能在创建时就给它们 malloc 内存了，而且这几个 tensor 是不会被加到 resize op 的 input 里的，因此只有在初始化算子时才会用到它们，即使之后再次 malloc 也不影响正确性。

2023-12-27 07:52 UTC, kilinchange commented on src/core/graph_handler.cc
> +                ResizeObj::fromENearestModeStr(nearestMode),
已修改。

2023-12-27 08:30 UTC, YdrMaster approved these changes

2023-12-27 09:46 UTC, bitzyz approved these changes

2023-12-29 05:29 UTC, whjthu approved these changes

2023-12-29 05:32 UTC, merged