[WIP] Modify kernel registration & support fp16
InfiniTensor/InfiniTensor pull request #205
Opened 2023-12-28 08:38 UTC by kilinchange

2024-01-02 07:52 UTC, kilinchange commented
`cd build/Release && make test
make[1]: Entering directory '/home/duanchenjie/workspace/InfiniTensor/build/Release'
Running tests...
Test project /home/duanchenjie/workspace/InfiniTensor/build/Release
      Start  1: test_graph
 1/71 Test  #1: test_graph .......................   Passed    0.05 sec
      Start  2: test_graph_handler
 2/71 Test  #2: test_graph_handler ...............   Passed    0.05 sec
      Start  3: test_graph_replace
 3/71 Test  #3: test_graph_replace ...............   Passed    0.05 sec
      Start  4: test_hash
 4/71 Test  #4: test_hash ........................   Passed    0.04 sec
      Start  5: test_lazy_allocator
 5/71 Test  #5: test_lazy_allocator ..............   Passed    0.05 sec
      Start  6: test_search
 6/71 Test  #6: test_search ......................   Passed    0.42 sec
      Start  7: test_tensor_save
 7/71 Test  #7: test_tensor_save .................   Passed    0.00 sec
      Start  8: test_verify
 8/71 Test  #8: test_verify ......................   Passed    0.05 sec
      Start  9: test_all_gather
 9/71 Test  #9: test_all_gather ..................   Passed    0.04 sec
      Start 10: test_all_reduce
10/71 Test #10: test_all_reduce ..................   Passed    0.04 sec
      Start 11: test_batch_norm
11/71 Test #11: test_batch_norm ..................   Passed    0.05 sec
      Start 12: test_broadcast
12/71 Test #12: test_broadcast ...................   Passed    0.05 sec
      Start 13: test_clip
13/71 Test #13: test_clip ........................   Passed    0.05 sec
      Start 14: test_concat
14/71 Test #14: test_concat ......................   Passed    0.05 sec
      Start 15: test_conv
15/71 Test #15: test_conv ........................   Passed    0.28 sec
      Start 16: test_conv_transposed_2d
16/71 Test #16: test_conv_transposed_2d ..........   Passed    0.04 sec
      Start 17: test_element_wise
17/71 Test #17: test_element_wise ................   Passed    0.04 sec
      Start 18: test_expand
18/71 Test #18: test_expand ......................   Passed    0.05 sec
      Start 19: test_extend
19/71 Test #19: test_extend ......................   Passed    0.04 sec
      Start 20: test_gather
20/71 Test #20: test_gather ......................   Passed    0.04 sec
      Start 21: test_gather_elements
21/71 Test #21: test_gather_elements .............   Passed    0.05 sec
      Start 22: test_matmul
22/71 Test #22: test_matmul ......................   Passed    0.05 sec
      Start 23: test_pad
23/71 Test #23: test_pad .........................   Passed    0.05 sec
      Start 24: test_pooling
24/71 Test #24: test_pooling .....................   Passed    0.05 sec
      Start 25: test_reduce
25/71 Test #25: test_reduce ......................   Passed    0.05 sec
      Start 26: test_reshape
26/71 Test #26: test_reshape .....................   Passed    0.05 sec
      Start 27: test_resize
27/71 Test #27: test_resize ......................   Passed    0.04 sec
      Start 28: test_sendrecv
28/71 Test #28: test_sendrecv ....................   Passed    0.05 sec
      Start 29: test_slice
29/71 Test #29: test_slice .......................   Passed    0.05 sec
      Start 30: test_split
30/71 Test #30: test_split .......................   Passed    0.05 sec
      Start 31: test_transpose
31/71 Test #31: test_transpose ...................   Passed    0.05 sec
      Start 32: test_unary
32/71 Test #32: test_unary .......................   Passed    0.05 sec
      Start 33: test_where
33/71 Test #33: test_where .......................   Passed    0.05 sec
      Start 34: test_nativecpu_concat
34/71 Test #34: test_nativecpu_concat ............   Passed    0.09 sec
      Start 35: test_nativecpu_split
35/71 Test #35: test_nativecpu_split .............   Passed    0.07 sec
      Start 36: test_nativecpu_transpose
36/71 Test #36: test_nativecpu_transpose .........   Passed    0.04 sec
      Start 37: test_cuda_G2BMM
37/71 Test #37: test_cuda_G2BMM ..................   Passed    2.55 sec
      Start 38: test_cuda_GBMM
38/71 Test #38: test_cuda_GBMM ...................   Passed    3.54 sec
      Start 39: test_cuda_all_gather
39/71 Test #39: test_cuda_all_gather .............   Passed    7.31 sec
      Start 40: test_cuda_all_reduce
40/71 Test #40: test_cuda_all_reduce .............   Passed   13.75 sec
      Start 41: test_cuda_attention
41/71 Test #41: test_cuda_attention ..............   Passed    3.24 sec
      Start 42: test_cuda_batch_norm
42/71 Test #42: test_cuda_batch_norm .............   Passed    0.50 sec
      Start 43: test_cuda_broadcast
43/71 Test #43: test_cuda_broadcast ..............   Passed    7.18 sec
      Start 44: test_cuda_clip
44/71 Test #44: test_cuda_clip ...................   Passed    3.37 sec
      Start 45: test_cuda_concat
45/71 Test #45: test_cuda_concat .................   Passed    3.52 sec
      Start 46: test_cuda_conv
46/71 Test #46: test_cuda_conv ...................   Passed    3.59 sec
      Start 47: test_cuda_conv_fp16
47/71 Test #47: test_cuda_conv_fp16 ..............   Passed    3.51 sec
      Start 48: test_cuda_conv_transposed_2d
48/71 Test #48: test_cuda_conv_transposed_2d .....   Passed    0.79 sec
      Start 49: test_cuda_element_wise
49/71 Test #49: test_cuda_element_wise ...........   Passed    3.43 sec
      Start 50: test_cuda_expand
50/71 Test #50: test_cuda_expand .................   Passed    3.39 sec
      Start 51: test_cuda_extend
51/71 Test #51: test_cuda_extend .................   Passed    3.40 sec
      Start 52: test_cuda_gather
52/71 Test #52: test_cuda_gather .................   Passed    0.60 sec
      Start 53: test_cuda_gather_elements
53/71 Test #53: test_cuda_gather_elements ........   Passed    3.32 sec
      Start 54: test_cuda_inception
54/71 Test #54: test_cuda_inception ..............   Passed    3.54 sec
      Start 55: test_cuda_layernorm
55/71 Test #55: test_cuda_layernorm ..............   Passed    3.53 sec
      Start 56: test_cuda_matmul
56/71 Test #56: test_cuda_matmul .................   Passed    3.61 sec
      Start 57: test_cuda_pad
57/71 Test #57: test_cuda_pad ....................   Passed    0.60 sec
      Start 58: test_cuda_pooling
58/71 Test #58: test_cuda_pooling ................   Passed    3.35 sec
      Start 59: test_cuda_reduce
59/71 Test #59: test_cuda_reduce .................   Passed    3.54 sec
      Start 60: test_cuda_reshape
60/71 Test #60: test_cuda_reshape ................   Passed    3.52 sec
      Start 61: test_cuda_resize
61/71 Test #61: test_cuda_resize .................   Passed    4.69 sec
      Start 62: test_cuda_sendrecv
62/71 Test #62: test_cuda_sendrecv ...............   Passed   17.25 sec
      Start 63: test_cuda_slice
63/71 Test #63: test_cuda_slice ..................   Passed    3.09 sec
      Start 64: test_cuda_softmax
64/71 Test #64: test_cuda_softmax ................   Passed    3.49 sec
      Start 65: test_cuda_split
65/71 Test #65: test_cuda_split ..................   Passed    0.59 sec
      Start 66: test_cuda_transpose
66/71 Test #66: test_cuda_transpose ..............   Passed    3.39 sec
      Start 67: test_cuda_unary
67/71 Test #67: test_cuda_unary ..................   Passed    3.45 sec
      Start 68: test_cuda_unary_fp16
68/71 Test #68: test_cuda_unary_fp16 .............   Passed    0.01 sec
      Start 69: test_cuda_where
69/71 Test #69: test_cuda_where ..................   Passed    0.63 sec
      Start 70: test_perfengine
70/71 Test #70: test_perfengine ..................   Passed    3.51 sec
      Start 71: test_nccl_comm
71/71 Test #71: test_nccl_comm ...................   Passed    7.30 sec

100% tests passed, 0 tests failed out of 71`

英伟达平台测试通过。

2024-01-02 07:59 UTC, bitzyz commented
![image](https://github.com/InfiniTensor/InfiniTensor/assets/93699316/4f1380fc-fb3b-45f0-b71b-019a45937fc4)
mlu测试无误

2024-01-03 01:57 UTC, bitzyz commented
昆仑平台测试无误

2024-01-10 03:20 UTC, wanghailu0717 approved these changes

2024-01-10 04:24 UTC, bitzyz requested changes

2024-01-11 03:44 UTC, kilinchange commented on examples/distributed/parallel_opt.py
> +        if node.op_type in ["Relu", "Tanh", "Softmax", "Cast"]:
这部分改动是适配 llama fp16 分布式的，还是合一下吧，int8 的部分我没加进来。

2024-01-11 03:49 UTC, kilinchange commented on src/kernels/cuda/gather.cu
> +    if (tid < num) {
@OdinaryWord

2024-01-11 03:52 UTC, kilinchange commented on src/kernels/cuda/all_reduce.cc
> +        }
fixed

2024-01-11 04:31 UTC, kilinchange commented on include/core/operator.h
> +    DataType getInDType() const { return getInputs(0)->getDType(); }
fixed

2024-01-12 05:39 UTC, kilinchange commented on src/kernels/cuda/gather.cu
> +    if (tid < num) {
之前的写法逻辑是不会进第二次while的，也就是说stride算着没意义。因为blockDim.x * gridDim.x >= num。

2024-01-12 06:14 UTC, OdinaryWord commented on src/kernels/cuda/gather.cu
> +    if (tid < num) {
之前的写法逻辑是不会进第二次while的，也就是说stride算着没意义。因为blockDim.x * gridDim.x >= num。

2024-01-12 06:24 UTC, bitzyz approved these changes

2024-01-15 03:01 UTC, whjthu approved these changes

2024-01-15 03:02 UTC, merged