解除前端对onnx infershape功能的依赖
InfiniTensor/InfiniTensor pull request #206
Opened 2024-01-02 05:38 UTC by bitzyz

1. 编译期新增squeeze、unsqueeze算子，不与reshape算子共用前端函数handler.reshape()
2. 对新增的squeeze、unsqueeze添加形状推导测试、onnx读入测试
3. onnx.py删除_search_shape函数，删除onnx导入的infer_shapes功能

2024-01-05 01:05 UTC, YdrMaster commented
其实不需要写 squeeze unsqueeze 算子，从 tensor 拿形状就行了，换个人推导而已

2024-01-08 08:25 UTC, kilinchange requested changes

2024-01-08 08:25 UTC, kilinchange commented on src/core/graph_handler.cc
> +Tensor GraphHandlerObj::squeeze(Tensor input, Tensor output, Shape axes) {
squeeze 的 axes 属性是 optional 的，这里应该写成 optional 类型吧

2024-01-08 08:28 UTC, bitzyz commented on src/core/graph_handler.cc
> +Tensor GraphHandlerObj::squeeze(Tensor input, Tensor output, Shape axes) {
这里是在前端支持传入为空的，当传入为空时在算子内部会遍历寻找所有为1的维度当作axes

2024-01-08 08:42 UTC, kilinchange approved these changes

2024-01-10 02:54 UTC, YdrMaster approved these changes

2024-01-12 06:54 UTC, whjthu approved these changes

2024-01-12 06:54 UTC, merged