fix mlu some kernel registration & gather op
InfiniTensor/InfiniTensor pull request #210
Opened 2024-01-17 05:48 UTC by bitzyz

2024-01-25 03:01 UTC, Chamberlain0w0 commented on src/kernels/bang/slice.cc
> +        IT_ASSERT(op->getDType() == DataType::Float32);
这个可以删掉，cnnlStridedSlice可以支持多精度

2024-01-25 03:02 UTC, Chamberlain0w0 commented on src/kernels/bang/all_gather.cc
> +        IT_ASSERT(op->getDType() == DataType::Float32);
这里也删掉

2024-01-25 03:02 UTC, Chamberlain0w0 commented on src/kernels/bang/all_reduce.cc
> +        IT_ASSERT(op->getDType() == DataType::Float32);
这里也删掉

2024-01-25 03:02 UTC, Chamberlain0w0 commented on src/kernels/bang/broadcast.cc
> +        IT_ASSERT(op->getDType() == DataType::Float32);
这里也删掉

2024-01-26 02:16 UTC, Chamberlain0w0 commented
修复的几个问题：
1. mlu370 和 mlu590 上的各自的编译问题，具体包括正确添加分布式编译选项以及对计算库版本号进行静态判定 (gather 算子)。现在除了 370 裸机上无法编译分布式以外 (无法使用 DIST=ON，但是 370 在 docker 容器中可以正常编译)，其他现有环境都可以编译通过；
2. redmine 上提到的精度问题，来自于之前某次合入 reshape 算子部分的冲突没有正常解决；
3. mobilenet_v3 模型跑不通，需要 hardsigmoid / hardswish 算子；
4. 修正了分布式算子对 fp16 的支持。

2024-01-26 02:18 UTC, Chamberlain0w0 commented
590 机器上，验证分布式 llama2 / gpt2 结果正确 （与单卡推理相比）：

![image](https://github.com/InfiniTensor/InfiniTensor/assets/48948016/a3153388-9ea1-4615-ab5b-2eb3be34feb5)
![image](https://github.com/InfiniTensor/InfiniTensor/assets/48948016/1c715d31-9d50-4e11-9f6c-debe48d02deb)

2024-01-26 02:31 UTC, Chamberlain0w0 commented
370 机器上，验证 TorchVision 若干模型推理结果正确（与 onnxruntime 相比，`np.testing.assert_allclose(rtol=1.0, atol=1e-5)` ）：

![image](https://github.com/InfiniTensor/InfiniTensor/assets/48948016/4d367772-995c-4454-a601-e2471786e648)

仍存在的问题：
1. maxvit 需要 Einsum 算子；
2. `regnet_y_128gf_bs1.onnx` 文件损坏，不过 regnet 系列其他模型推理结果没问题。

2024-01-26 02:31 UTC, Chamberlain0w0 commented
370 上单测结果：

![image](https://github.com/InfiniTensor/InfiniTensor/assets/48948016/c9c740d1-bf66-40da-b481-93999d0fe17d)

590 上单测结果：

![image](https://github.com/InfiniTensor/InfiniTensor/assets/48948016/a33a903d-b0b2-48a9-847e-4a2d9eb6ca56)

2024-01-26 02:59 UTC, wanghailu0717 commented on include/bang/bang_common.h
> +        return cnclUint32;
?

2024-01-26 03:10 UTC, kilinchange approved these changes

2024-01-26 03:18 UTC, wanghailu0717 approved these changes

2024-01-29 00:57 UTC, whjthu requested changes

2024-01-29 00:57 UTC, whjthu commented on include/bang/bang_common.h
> +    return cnclInvalid;
这个没有在外面处理错误，所以应该在这里就直接 assert 掉吧

2024-01-29 06:10 UTC, Chamberlain0w0 requested changes
HuggingFace模型和个别古早CV模型结果与runtime相比还有错误。

2024-01-30 02:27 UTC, whjthu approved these changes

2024-01-31 05:07 UTC, Chamberlain0w0 approved these changes

2024-01-31 05:23 UTC, Chamberlain0w0 commented
HuggingFace 模型和其他 CV 模型推理结果正确（与 onnxruntime 相比，`np.testing.assert_allclose(rtol=1.0, atol=1e-5)` ）：
![image](https://github.com/InfiniTensor/InfiniTensor/assets/48948016/40352962-2a98-4c44-949b-b2cac7d1b594)
![image](https://github.com/InfiniTensor/InfiniTensor/assets/48948016/a830880f-1fd9-436c-a761-578f58dc6dd2)

仍存在的问题：
1. esrgan 需要 LeakyRelu 算子；
2. fsrcnn 模型最后一个 ConvTranspose 的 bias 输入不为 0，目前框架 ConvTranspose 的前端未考虑有 bias 的情况。

2024-02-01 07:02 UTC, merged