support more data type on mlu
InfiniTensor/InfiniTensor pull request #211
Opened 2024-01-19 06:00 UTC by wanghailu0717

2024-01-19 06:01 UTC, wanghailu0717 commented
测试报告
```
Running tests...
Test project /home/wanghailu/InfiniTensor/build/Release
      Start  1: test_graph
 1/81 Test  #1: test_graph .......................   Passed    0.02 sec
      Start  2: test_graph_handler
 2/81 Test  #2: test_graph_handler ...............   Passed    0.02 sec
      Start  3: test_graph_replace
 3/81 Test  #3: test_graph_replace ...............   Passed    0.02 sec
      Start  4: test_hash
 4/81 Test  #4: test_hash ........................   Passed    0.02 sec
      Start  5: test_lazy_allocator
 5/81 Test  #5: test_lazy_allocator ..............   Passed    0.02 sec
      Start  6: test_search
 6/81 Test  #6: test_search ......................   Passed    0.62 sec
      Start  7: test_tensor_save
 7/81 Test  #7: test_tensor_save .................   Passed    0.00 sec
      Start  8: test_verify
 8/81 Test  #8: test_verify ......................   Passed    0.02 sec
      Start  9: test_all_gather
 9/81 Test  #9: test_all_gather ..................   Passed    0.02 sec
      Start 10: test_all_reduce
10/81 Test #10: test_all_reduce ..................   Passed    0.02 sec
      Start 11: test_batch_norm
11/81 Test #11: test_batch_norm ..................   Passed    0.02 sec
      Start 12: test_broadcast
12/81 Test #12: test_broadcast ...................   Passed    0.02 sec
      Start 13: test_clip
13/81 Test #13: test_clip ........................   Passed    0.02 sec
      Start 14: test_concat
14/81 Test #14: test_concat ......................   Passed    0.02 sec
      Start 15: test_conv
15/81 Test #15: test_conv ........................   Passed    0.08 sec
      Start 16: test_conv_transposed_2d
16/81 Test #16: test_conv_transposed_2d ..........   Passed    0.02 sec
      Start 17: test_element_wise
17/81 Test #17: test_element_wise ................   Passed    0.02 sec
      Start 18: test_expand
18/81 Test #18: test_expand ......................   Passed    0.02 sec
      Start 19: test_extend
19/81 Test #19: test_extend ......................   Passed    0.02 sec
      Start 20: test_gather
20/81 Test #20: test_gather ......................   Passed    0.02 sec
      Start 21: test_gather_elements
21/81 Test #21: test_gather_elements .............   Passed    0.02 sec
      Start 22: test_matmul
22/81 Test #22: test_matmul ......................   Passed    0.02 sec
      Start 23: test_pad
23/81 Test #23: test_pad .........................   Passed    0.02 sec
      Start 24: test_pooling
24/81 Test #24: test_pooling .....................   Passed    0.02 sec
      Start 25: test_reduce
25/81 Test #25: test_reduce ......................   Passed    0.02 sec
      Start 26: test_reshape
26/81 Test #26: test_reshape .....................   Passed    0.02 sec
      Start 27: test_resize
27/81 Test #27: test_resize ......................   Passed    0.02 sec
      Start 28: test_sendrecv
28/81 Test #28: test_sendrecv ....................   Passed    0.02 sec
      Start 29: test_slice
29/81 Test #29: test_slice .......................   Passed    0.02 sec
      Start 30: test_split
30/81 Test #30: test_split .......................   Passed    0.02 sec
      Start 31: test_transpose
31/81 Test #31: test_transpose ...................   Passed    0.02 sec
      Start 32: test_unary
32/81 Test #32: test_unary .......................   Passed    0.02 sec
      Start 33: test_where
33/81 Test #33: test_where .......................   Passed    0.02 sec
      Start 34: test_nativecpu_concat
34/81 Test #34: test_nativecpu_concat ............   Passed    0.05 sec
      Start 35: test_nativecpu_elementwise
35/81 Test #35: test_nativecpu_elementwise .......   Passed    0.02 sec
      Start 36: test_nativecpu_split
36/81 Test #36: test_nativecpu_split .............   Passed    0.04 sec
      Start 37: test_nativecpu_transpose
37/81 Test #37: test_nativecpu_transpose .........   Passed    0.02 sec
      Start 38: test_bang_activation_backward
38/81 Test #38: test_bang_activation_backward ....   Passed    2.37 sec
      Start 39: test_bang_all_gather
39/81 Test #39: test_bang_all_gather .............   Passed    0.00 sec
      Start 40: test_bang_all_reduce
40/81 Test #40: test_bang_all_reduce .............   Passed    0.00 sec
      Start 41: test_bang_bangcKernel
41/81 Test #41: test_bang_bangcKernel ............   Passed    2.16 sec
      Start 42: test_bang_batch_norm
42/81 Test #42: test_bang_batch_norm .............   Passed    2.36 sec
      Start 43: test_bang_bitcompute
43/81 Test #43: test_bang_bitcompute .............   Passed    2.18 sec
      Start 44: test_bang_broadcast
44/81 Test #44: test_bang_broadcast ..............   Passed    0.00 sec
      Start 45: test_bang_cast
45/81 Test #45: test_bang_cast ...................   Passed    2.16 sec
      Start 46: test_bang_ceil
46/81 Test #46: test_bang_ceil ...................   Passed    2.43 sec
      Start 47: test_bang_clip
47/81 Test #47: test_bang_clip ...................   Passed    2.17 sec
      Start 48: test_bang_concat
48/81 Test #48: test_bang_concat .................   Passed    2.36 sec
      Start 49: test_bang_conv
49/81 Test #49: test_bang_conv ...................   Passed    2.19 sec
      Start 50: test_bang_det
50/81 Test #50: test_bang_det ....................   Passed    2.39 sec
      Start 51: test_bang_element_wise
51/81 Test #51: test_bang_element_wise ...........   Passed    2.16 sec
      Start 52: test_bang_erf
52/81 Test #52: test_bang_erf ....................   Passed    2.38 sec
      Start 53: test_bang_exp
53/81 Test #53: test_bang_exp ....................   Passed    2.17 sec
      Start 54: test_bang_fill
54/81 Test #54: test_bang_fill ...................   Passed    2.38 sec
      Start 55: test_bang_floor
55/81 Test #55: test_bang_floor ..................   Passed    2.18 sec
      Start 56: test_bang_hardtanh
56/81 Test #56: test_bang_hardtanh ...............   Passed    2.17 sec
      Start 57: test_bang_l2loss
57/81 Test #57: test_bang_l2loss .................   Passed    2.15 sec
      Start 58: test_bang_log
58/81 Test #58: test_bang_log ....................   Passed    2.19 sec
      Start 59: test_bang_logic
59/81 Test #59: test_bang_logic ..................   Passed    2.17 sec
      Start 60: test_bang_matmul
60/81 Test #60: test_bang_matmul .................   Passed    2.19 sec
      Start 61: test_bang_maximum
61/81 Test #61: test_bang_maximum ................   Passed    2.16 sec
      Start 62: test_bang_minimum
62/81 Test #62: test_bang_minimum ................   Passed    2.16 sec
      Start 63: test_bang_mseloss
63/81 Test #63: test_bang_mseloss ................   Passed    2.17 sec
      Start 64: test_bang_neg
64/81 Test #64: test_bang_neg ....................   Passed    2.19 sec
      Start 65: test_bang_net
65/81 Test #65: test_bang_net ....................   Passed    2.15 sec
      Start 66: test_bang_optensor
66/81 Test #66: test_bang_optensor ...............   Passed    2.16 sec
      Start 67: test_bang_pad
67/81 Test #67: test_bang_pad ....................   Passed    2.17 sec
      Start 68: test_bang_pooling
68/81 Test #68: test_bang_pooling ................   Passed    2.17 sec
      Start 69: test_bang_pow
69/81 Test #69: test_bang_pow ....................   Passed    2.21 sec
      Start 70: test_bang_prelu
70/81 Test #70: test_bang_prelu ..................   Passed    2.18 sec
      Start 71: test_bang_reciprocal
71/81 Test #71: test_bang_reciprocal .............   Passed    2.17 sec
      Start 72: test_bang_reduce
72/81 Test #72: test_bang_reduce .................   Passed    2.17 sec
      Start 73: test_bang_round
73/81 Test #73: test_bang_round ..................   Passed    2.16 sec
      Start 74: test_bang_slice
74/81 Test #74: test_bang_slice ..................   Passed    2.16 sec
      Start 75: test_bang_softmax
75/81 Test #75: test_bang_softmax ................   Passed    2.17 sec
      Start 76: test_bang_split
76/81 Test #76: test_bang_split ..................   Passed    2.16 se [...]

2024-01-19 06:44 UTC, Chamberlain0w0 approved these changes

2024-01-19 07:14 UTC, wanghailu0717 commented
测试报告
```
Running tests...
Test project /home/wanghailu/InfiniTensor/build/Release
      Start  1: test_graph
 1/81 Test  #1: test_graph .......................   Passed    0.02 sec
      Start  2: test_graph_handler
 2/81 Test  #2: test_graph_handler ...............   Passed    0.02 sec
      Start  3: test_graph_replace
 3/81 Test  #3: test_graph_replace ...............   Passed    0.03 sec
      Start  4: test_hash
 4/81 Test  #4: test_hash ........................   Passed    0.02 sec
      Start  5: test_lazy_allocator
 5/81 Test  #5: test_lazy_allocator ..............   Passed    0.02 sec
      Start  6: test_search
 6/81 Test  #6: test_search ......................   Passed    0.63 sec
      Start  7: test_tensor_save
 7/81 Test  #7: test_tensor_save .................   Passed    0.00 sec
      Start  8: test_verify
 8/81 Test  #8: test_verify ......................   Passed    0.02 sec
      Start  9: test_all_gather
 9/81 Test  #9: test_all_gather ..................   Passed    0.02 sec
      Start 10: test_all_reduce
10/81 Test #10: test_all_reduce ..................   Passed    0.02 sec
      Start 11: test_batch_norm
11/81 Test #11: test_batch_norm ..................   Passed    0.02 sec
      Start 12: test_broadcast
12/81 Test #12: test_broadcast ...................   Passed    0.02 sec
      Start 13: test_clip
13/81 Test #13: test_clip ........................   Passed    0.02 sec
      Start 14: test_concat
14/81 Test #14: test_concat ......................   Passed    0.02 sec
      Start 15: test_conv
15/81 Test #15: test_conv ........................   Passed    0.08 sec
      Start 16: test_conv_transposed_2d
16/81 Test #16: test_conv_transposed_2d ..........   Passed    0.02 sec
      Start 17: test_element_wise
17/81 Test #17: test_element_wise ................   Passed    0.02 sec
      Start 18: test_expand
18/81 Test #18: test_expand ......................   Passed    0.02 sec
      Start 19: test_extend
19/81 Test #19: test_extend ......................   Passed    0.02 sec
      Start 20: test_gather
20/81 Test #20: test_gather ......................   Passed    0.02 sec
      Start 21: test_gather_elements
21/81 Test #21: test_gather_elements .............   Passed    0.02 sec
      Start 22: test_matmul
22/81 Test #22: test_matmul ......................   Passed    0.02 sec
      Start 23: test_pad
23/81 Test #23: test_pad .........................   Passed    0.02 sec
      Start 24: test_pooling
24/81 Test #24: test_pooling .....................   Passed    0.02 sec
      Start 25: test_reduce
25/81 Test #25: test_reduce ......................   Passed    0.02 sec
      Start 26: test_reshape
26/81 Test #26: test_reshape .....................   Passed    0.02 sec
      Start 27: test_resize
27/81 Test #27: test_resize ......................   Passed    0.02 sec
      Start 28: test_sendrecv
28/81 Test #28: test_sendrecv ....................   Passed    0.02 sec
      Start 29: test_slice
29/81 Test #29: test_slice .......................   Passed    0.02 sec
      Start 30: test_split
30/81 Test #30: test_split .......................   Passed    0.02 sec
      Start 31: test_transpose
31/81 Test #31: test_transpose ...................   Passed    0.02 sec
      Start 32: test_unary
32/81 Test #32: test_unary .......................   Passed    0.02 sec
      Start 33: test_where
33/81 Test #33: test_where .......................   Passed    0.02 sec
      Start 34: test_nativecpu_concat
34/81 Test #34: test_nativecpu_concat ............   Passed    0.04 sec
      Start 35: test_nativecpu_elementwise
35/81 Test #35: test_nativecpu_elementwise .......   Passed    0.02 sec
      Start 36: test_nativecpu_split
36/81 Test #36: test_nativecpu_split .............   Passed    0.05 sec
      Start 37: test_nativecpu_transpose
37/81 Test #37: test_nativecpu_transpose .........   Passed    0.02 sec
      Start 38: test_bang_activation_backward
38/81 Test #38: test_bang_activation_backward ....   Passed    2.23 sec
      Start 39: test_bang_all_gather
39/81 Test #39: test_bang_all_gather .............   Passed    0.00 sec
      Start 40: test_bang_all_reduce
40/81 Test #40: test_bang_all_reduce .............   Passed    0.00 sec
      Start 41: test_bang_bangcKernel
41/81 Test #41: test_bang_bangcKernel ............   Passed    2.19 sec
      Start 42: test_bang_batch_norm
42/81 Test #42: test_bang_batch_norm .............   Passed    2.17 sec
      Start 43: test_bang_bitcompute
43/81 Test #43: test_bang_bitcompute .............   Passed    2.28 sec
      Start 44: test_bang_broadcast
44/81 Test #44: test_bang_broadcast ..............   Passed    0.00 sec
      Start 45: test_bang_cast
45/81 Test #45: test_bang_cast ...................   Passed    2.17 sec
      Start 46: test_bang_ceil
46/81 Test #46: test_bang_ceil ...................   Passed    2.18 sec
      Start 47: test_bang_clip
47/81 Test #47: test_bang_clip ...................   Passed    2.24 sec
      Start 48: test_bang_concat
48/81 Test #48: test_bang_concat .................   Passed    2.27 sec
      Start 49: test_bang_conv
49/81 Test #49: test_bang_conv ...................   Passed    2.29 sec
      Start 50: test_bang_det
50/81 Test #50: test_bang_det ....................   Passed    2.16 sec
      Start 51: test_bang_element_wise
51/81 Test #51: test_bang_element_wise ...........   Passed    2.16 sec
      Start 52: test_bang_erf
52/81 Test #52: test_bang_erf ....................   Passed    2.19 sec
      Start 53: test_bang_exp
53/81 Test #53: test_bang_exp ....................   Passed    2.16 sec
      Start 54: test_bang_fill
54/81 Test #54: test_bang_fill ...................   Passed    2.17 sec
      Start 55: test_bang_floor
55/81 Test #55: test_bang_floor ..................   Passed    2.18 sec
      Start 56: test_bang_hardtanh
56/81 Test #56: test_bang_hardtanh ...............   Passed    2.18 sec
      Start 57: test_bang_l2loss
57/81 Test #57: test_bang_l2loss .................   Passed    2.17 sec
      Start 58: test_bang_log
58/81 Test #58: test_bang_log ....................   Passed    2.18 sec
      Start 59: test_bang_logic
59/81 Test #59: test_bang_logic ..................   Passed    2.19 sec
      Start 60: test_bang_matmul
60/81 Test #60: test_bang_matmul .................   Passed    2.17 sec
      Start 61: test_bang_maximum
61/81 Test #61: test_bang_maximum ................   Passed    2.18 sec
      Start 62: test_bang_minimum
62/81 Test #62: test_bang_minimum ................   Passed    2.17 sec
      Start 63: test_bang_mseloss
63/81 Test #63: test_bang_mseloss ................   Passed    2.18 sec
      Start 64: test_bang_neg
64/81 Test #64: test_bang_neg ....................   Passed    2.31 sec
      Start 65: test_bang_net
65/81 Test #65: test_bang_net ....................   Passed    2.16 sec
      Start 66: test_bang_optensor
66/81 Test #66: test_bang_optensor ...............   Passed    2.17 sec
      Start 67: test_bang_pad
67/81 Test #67: test_bang_pad ....................   Passed    2.16 sec
      Start 68: test_bang_pooling
68/81 Test #68: test_bang_pooling ................   Passed    2.17 sec
      Start 69: test_bang_pow
69/81 Test #69: test_bang_pow ....................   Passed    2.16 sec
      Start 70: test_bang_prelu
70/81 Test #70: test_bang_prelu ..................   Passed    2.18 sec
      Start 71: test_bang_reciprocal
71/81 Test #71: test_bang_reciprocal .............   Passed    2.25 sec
      Start 72: test_bang_reduce
72/81 Test #72: test_bang_reduce .................   Passed    2.19 sec
      Start 73: test_bang_round
73/81 Test #73: test_bang_round ..................   Passed    2.18 sec
      Start 74: test_bang_slice
74/81 Test #74: test_bang_slice ..................   Passed    2.17 sec
      Start 75: test_bang_softmax
75/81 Test #75: test_bang_softmax ................   Passed    2.18 sec
      Start 76: test_bang_split
76/81 Test #76: test_bang_split ..................   Passed    2.16 se [...]

2024-01-19 07:57 UTC, kilinchange requested changes
另外建议拿变量存一下 cnnlDataTypeConvert(op->getDType()) 的值，否则每次传参都调一遍函数会引入额外时间开销吧。

2024-01-19 07:57 UTC, kilinchange commented on src/kernels/bang/all_gather.cc
cnclAllGather 有个参数传的是数据类型，是不是也应该转换成正确的类型？

2024-01-19 07:57 UTC, kilinchange commented on src/kernels/bang/all_reduce.cc
cnclAllReduce 传入的数据类型也应该转成正确的类型吧？

2024-01-19 07:57 UTC, kilinchange commented on src/kernels/bang/broadcast.cc
cnclBroadcast 传的数据类型还是 float32。

2024-01-24 02:19 UTC, wanghailu0717 commented
> 量存一下 cnnlDataTypeConvert(op->getDType()) 的值，否则每次传参都调一遍函数会引入额外时间开销吧。

我认为没必要，理由如下：

2024-01-24 03:27 UTC, kilinchange approved these changes

2024-01-24 05:33 UTC, merged