feat: add reshape/identity/squeeze/flatten/unsqueeze op cpu kernel
InfiniTensor/InfiniTensor pull request #213
Opened 2024-01-22 03:36 UTC by bitzyz

add reshape/identity/squeeze/flatten/unsqueeze op cpu kernel

2024-01-25 07:09 UTC, kilinchange requested changes

2024-01-25 07:09 UTC, kilinchange commented on src/kernels/cpu/reshape.cc
> +                  _op->getDType().getIndex() == 12);
理论上这个算子可以支持所有精度类型吧，这里就不需要过滤了

2024-01-29 01:31 UTC, bitzyz commented on src/kernels/cpu/reshape.cc
> +                  _op->getDType().getIndex() == 12);
当时是为了跟其它cpu算子对齐，已删除

2024-01-29 01:58 UTC, kilinchange approved these changes

2024-01-30 02:29 UTC, whjthu approved these changes

2024-01-30 02:29 UTC, merged