Rope and silu
InfiniTensor/InfiniTensor pull request #214
Opened 2024-01-30 07:31 UTC by xiaonans

添加silu和rotary embedding算子的支持。

2024-02-01 07:10 UTC, xgqdut2016 commented on src/kernels/cuda/unary.cu
> +    for (int i = index; i < n; i += stride) {
这个循环没有必要吧，直接写if(index < n)是不是就解决了

2024-02-01 07:16 UTC, xiaonans commented on src/kernels/cuda/unary.cu
> +    for (int i = index; i < n; i += stride) {
> 这个循环没有必要吧，直接写if(index < n)是不是就解决了

是的，如果外面调用的时候gridsize按照 (N+blocksize-1)/blocksize是没有必要写这个for循环；不过里面加上这个for循环，也是算子内部的一种双重保险，以免外面调用算子时gridsize给一个更小的值。

2024-02-02 03:21 UTC, kilinchange requested changes

2024-02-04 02:33 UTC, xiaonans commented on include/operators/rope.h
感谢建议，已经在代码rope代码中添加注释。

2024-02-04 02:36 UTC, whjthu approved these changes

2024-02-04 02:40 UTC, kilinchange commented on include/operators/rope.h
好像没有看到，是没推上来吗？

2024-02-04 02:43 UTC, kilinchange approved these changes

2024-02-04 03:05 UTC, xiaonans commented on include/operators/rope.h
现在应该推上来了。[include/operators/rope.h](https://github.com/InfiniTensor/InfiniTensor/pull/214/files#diff-5380277ee7bd34bbe2f826e3133074020d033fd9566b08d3af8d05425bb06337)

2024-02-04 03:05 UTC, merged