[feature] add cudagraph support
InfiniTensor/InfiniTensor pull request #215
Opened 2024-02-06 02:48 UTC by xiaonans

Passed all cuda related tests:
cd build/Release && make test
make[1]: Entering directory '/home/songxiaonan/projects/InfiniTensor/build/Release'
Running tests...
Test project /home/songxiaonan/projects/InfiniTensor/build/Release
      Start  1: test_graph
 1/74 Test  #1: test_graph .......................   Passed    0.05 sec
      Start  2: test_graph_handler
 2/74 Test  #2: test_graph_handler ...............   Passed    0.04 sec
      Start  3: test_graph_replace
 3/74 Test  #3: test_graph_replace ...............   Passed    0.04 sec
      Start  4: test_hash
 4/74 Test  #4: test_hash ........................   Passed    0.04 sec
      Start  5: test_lazy_allocator
 5/74 Test  #5: test_lazy_allocator ..............   Passed    0.04 sec
      Start  6: test_search
 6/74 Test  #6: test_search ......................   Passed    0.41 sec
      Start  7: test_tensor_save
 7/74 Test  #7: test_tensor_save .................   Passed    0.00 sec
      Start  8: test_verify
 8/74 Test  #8: test_verify ......................   Passed    0.04 sec
      Start  9: test_all_gather
 9/74 Test  #9: test_all_gather ..................   Passed    0.04 sec
      Start 10: test_all_reduce
10/74 Test #10: test_all_reduce ..................   Passed    0.04 sec
      Start 11: test_batch_norm
11/74 Test #11: test_batch_norm ..................   Passed    0.04 sec
      Start 12: test_broadcast
12/74 Test #12: test_broadcast ...................   Passed    0.04 sec
      Start 13: test_clip
13/74 Test #13: test_clip ........................   Passed    0.04 sec
      Start 14: test_concat
14/74 Test #14: test_concat ......................   Passed    0.04 sec
      Start 15: test_conv
15/74 Test #15: test_conv ........................   Passed    0.12 sec
      Start 16: test_conv_transposed_2d
16/74 Test #16: test_conv_transposed_2d ..........   Passed    0.04 sec
      Start 17: test_element_wise
17/74 Test #17: test_element_wise ................   Passed    0.04 sec
      Start 18: test_expand
18/74 Test #18: test_expand ......................   Passed    0.04 sec
      Start 19: test_extend
19/74 Test #19: test_extend ......................   Passed    0.04 sec
      Start 20: test_gather
20/74 Test #20: test_gather ......................   Passed    0.04 sec
      Start 21: test_gather_elements
21/74 Test #21: test_gather_elements .............   Passed    0.04 sec
      Start 22: test_matmul
22/74 Test #22: test_matmul ......................   Passed    0.04 sec
      Start 23: test_pad
23/74 Test #23: test_pad .........................   Passed    0.04 sec
      Start 24: test_pooling
24/74 Test #24: test_pooling .....................   Passed    0.04 sec
      Start 25: test_reduce
25/74 Test #25: test_reduce ......................   Passed    0.05 sec
      Start 26: test_reshape
26/74 Test #26: test_reshape .....................   Passed    0.04 sec
      Start 27: test_resize
27/74 Test #27: test_resize ......................   Passed    0.04 sec
      Start 28: test_sendrecv
28/74 Test #28: test_sendrecv ....................   Passed    0.04 sec
      Start 29: test_slice
29/74 Test #29: test_slice .......................   Passed    0.04 sec
      Start 30: test_split
30/74 Test #30: test_split .......................   Passed    0.04 sec
      Start 31: test_transpose
31/74 Test #31: test_transpose ...................   Passed    0.04 sec
      Start 32: test_unary
32/74 Test #32: test_unary .......................   Passed    0.04 sec
      Start 33: test_where
33/74 Test #33: test_where .......................   Passed    0.04 sec
      Start 34: test_nativecpu_concat
34/74 Test #34: test_nativecpu_concat ............   Passed    0.08 sec
      Start 35: test_nativecpu_elementwise
35/74 Test #35: test_nativecpu_elementwise .......   Passed    0.04 sec
      Start 36: test_nativecpu_identity
36/74 Test #36: test_nativecpu_identity ..........   Passed    0.04 sec
      Start 37: test_nativecpu_split
37/74 Test #37: test_nativecpu_split .............   Passed    0.05 sec
      Start 38: test_nativecpu_transpose
38/74 Test #38: test_nativecpu_transpose .........   Passed    0.04 sec
      Start 39: test_cuda_G2BMM
39/74 Test #39: test_cuda_G2BMM ..................   Passed    1.48 sec
      Start 40: test_cuda_GBMM
40/74 Test #40: test_cuda_GBMM ...................   Passed    2.89 sec
      Start 41: test_cuda_all_gather
41/74 Test #41: test_cuda_all_gather .............   Passed    5.13 sec
      Start 42: test_cuda_all_reduce
42/74 Test #42: test_cuda_all_reduce .............   Passed    5.05 sec
      Start 43: test_cuda_attention
43/74 Test #43: test_cuda_attention ..............   Passed    2.04 sec
      Start 44: test_cuda_batch_norm
44/74 Test #44: test_cuda_batch_norm .............   Passed    2.66 sec
      Start 45: test_cuda_broadcast
45/74 Test #45: test_cuda_broadcast ..............   Passed    5.14 sec
      Start 46: test_cuda_clip
46/74 Test #46: test_cuda_clip ...................   Passed    2.04 sec
      Start 47: test_cuda_concat
47/74 Test #47: test_cuda_concat .................   Passed    2.26 sec
      Start 48: test_cuda_conv
48/74 Test #48: test_cuda_conv ...................   Passed    2.98 sec
      Start 49: test_cuda_conv_fp16
49/74 Test #49: test_cuda_conv_fp16 ..............   Passed    2.80 sec
      Start 50: test_cuda_conv_transposed_2d
50/74 Test #50: test_cuda_conv_transposed_2d .....   Passed    2.91 sec
      Start 51: test_cuda_element_wise
51/74 Test #51: test_cuda_element_wise ...........   Passed    2.83 sec
      Start 52: test_cuda_expand
52/74 Test #52: test_cuda_expand .................   Passed    2.78 sec
      Start 53: test_cuda_extend
53/74 Test #53: test_cuda_extend .................   Passed    2.72 sec
      Start 54: test_cuda_gather
54/74 Test #54: test_cuda_gather .................   Passed    2.52 sec
      Start 55: test_cuda_gather_elements
55/74 Test #55: test_cuda_gather_elements ........   Passed    2.38 sec
      Start 56: test_cuda_inception
56/74 Test #56: test_cuda_inception ..............   Passed    2.62 sec
      Start 57: test_cuda_layernorm
57/74 Test #57: test_cuda_layernorm ..............   Passed    2.35 sec
      Start 58: test_cuda_matmul
58/74 Test #58: test_cuda_matmul .................   Passed    2.80 sec
      Start 59: test_cuda_pad
59/74 Test #59: test_cuda_pad ....................   Passed    2.78 sec
      Start 60: test_cuda_pooling
60/74 Test #60: test_cuda_pooling ................   Passed    2.76 sec
      Start 61: test_cuda_reduce
61/74 Test #61: test_cuda_reduce .................   Passed    3.06 sec
      Start 62: test_cuda_reshape
62/74 Test #62: test_cuda_reshape ................   Passed    2.80 sec
      Start 63: test_cuda_resize
63/74 Test #63: test_cuda_resize .................   Passed    5.01 sec
      Start 64: test_cuda_rope
64/74 Test #64: test_cuda_rope ...................   Passed    2.96 sec
      Start 65: test_cuda_sendrecv
65/74 Test #65: test_cuda_sendrecv ...............   Passed    6.80 sec
      Start 66: test_cuda_slice
66/74 Test #66: test_cuda_slice ..................   Passed    2.02 sec
      Start 67: test_cuda_softmax
67/74 Test #67: test_cuda_softmax ................   Passed    2.29 sec
      Start 68: test_cuda_split
68/74 Test #68: test_cuda_split ..................   Passed    2.53 sec
      Start 69: test_cuda_transpose
69/74 Test #69: test_cuda_transpose ..............   Passed    2.79 sec
      Start 70: test_cuda_unary
70/74 Test #70: test_cuda_unary ..................   Passed    4.48 sec
      Start 71: test_cuda_where
71/74 Test #71: test_cuda_where ..................   Passed    3.33 sec
      Start 72: test_perfengine
72/74 Test #72: test_perfengine ..................   Passed    2.56 sec
      Start 73: test_cudagraph
73/74 Test #73: test_cudagraph ...................   Passed    2.16 sec
      Start 74: test_nccl_comm
74/74 Test #74: test_nccl_comm ...................   Passed    4.66 sec

100% tests passed, 0 tests f [...]

2024-02-19 06:30 UTC, bitzyz requested changes

2024-02-19 06:30 UTC, bitzyz commented on src/cuda/cuda_runtime.cc
> +            cudaGraphLaunch(cudaGraphInstance, CUDAStream::getCurrentStream()));
为什么走if分支的话就不需要调用cudaGraphLaunch

2024-02-19 06:30 UTC, bitzyz commented on test/cuda/test_cudagraph.cc
> +    cudaRuntime->runWithCudaGraph(gCuda);
这里提前跑两次是为了预热吗

2024-02-19 09:12 UTC, xiaonans commented on test/cuda/test_cudagraph.cc
> +    cudaRuntime->runWithCudaGraph(gCuda);
是的，第一次跑会构造cudagraph，后面再跑会快一些。

2024-02-19 10:09 UTC, YdrMaster approved these changes

2024-02-20 01:34 UTC, bitzyz approved these changes

2024-02-21 06:00 UTC, whjthu approved these changes

2024-02-21 06:00 UTC, merged