bang-softmax operator
InfiniTensor/InfiniTensor pull request #217
Opened 2024-02-22 02:36 UTC by xgqdut2016

2024-02-23 07:35 UTC, wanghailu0717 approved these changes

2024-02-23 08:59 UTC, xiaonans approved these changes

2024-02-23 15:06 UTC, whjthu requested changes
光强说要再做些测试再合并，我就先 block 住了，另外注释需要改成英文

2024-02-28 03:33 UTC, xgqdut2016 commented
![微信截图_20240228113249](https://github.com/InfiniTensor/InfiniTensor/assets/140036308/4aa76fe1-5bb2-4776-99f5-206e0b967c9e)

2024-02-28 03:38 UTC, xgqdut2016 commented
![微信截图_20240228113754](https://github.com/InfiniTensor/InfiniTensor/assets/140036308/eb54c85f-a471-4684-a10d-9e6f4668fdc2)

2024-02-29 07:28 UTC, xgqdut2016 commented
<img width="790" alt="1709191675489" src="https://github.com/InfiniTensor/InfiniTensor/assets/140036308/6bbd749e-22ed-4941-9033-75f1bb1a0c61">

2024-03-06 01:39 UTC, xgqdut2016 commented
<img width="680" alt="1709689179490" src="https://github.com/InfiniTensor/InfiniTensor/assets/140036308/810d9304-ac77-42f3-909f-53e08df1f6d4">

2024-06-28 03:43 UTC, closed without merging