Accelerate llama
InfiniTensor/InfiniTensor pull request #219
Opened 2024-03-13 09:11 UTC by xiaonans

[feature] add rmsnorm and silu fusion

2024-03-26 06:52 UTC, xgqdut2016 commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +        # try:
为什么这段代码注释掉了，难道不需要检验运行过程中可能的错误了么

2024-03-28 06:16 UTC, kilinchange requested changes

2024-03-28 06:16 UTC, kilinchange commented on src/kernels/cuda/rope.cc
> +        int dim_head = 128;
这里为什么改成 128 了，而不是根据模型输入计算？

2024-03-28 06:47 UTC, xiaonans commented on src/kernels/cuda/rope.cc
> +        int dim_head = 128;
目前这个RoPE算子没有办法从框架获取它的形状，或许在这个算子前面强制加Reshape是一种解决方案，后面可以再讨论一下看看。

2024-03-29 06:50 UTC, kilinchange approved these changes

2024-03-29 06:54 UTC, xgqdut2016 approved these changes

2024-04-01 00:46 UTC, whjthu approved these changes

2024-04-01 00:46 UTC, merged