针对bert和gpt2模型分布式推理的优化
InfiniTensor/InfiniTensor pull request #221
Opened 2024-03-21 08:36 UTC by PanZezhong1725

1. 改善分布式脚本
2. 添加pytorch运行脚本
3. where算子优化
4. pow和div算子优化

2024-03-26 06:59 UTC, YdrMaster approved these changes

2024-03-28 05:56 UTC, kilinchange requested changes

2024-03-28 05:56 UTC, kilinchange commented on src/kernels/cuda/element_wise.cu
> +template <>
上面有模板类的 _pow_const_kernel 了，为什么这里还要写 half 类型的 kernel 呢？

2024-03-28 05:56 UTC, kilinchange commented on src/kernels/cuda/expand.cu
> +template <class Tmem>
Tmem 是什么缩写？

2024-03-28 05:56 UTC, kilinchange commented on src/kernels/cuda/expand.cu
> +    auto // dn = gridDim.y, // useless
不需要的注释直接删了吧

2024-03-28 05:56 UTC, kilinchange commented on include/cuda/cuda_expand.h
> +void expandRowKernel(int dType, void *input, void *output, int n_rows,
建议函数签名前加个注释强调一下，这个 kernel 只支持 n_rows 是 32 倍数的情况。

2024-03-28 06:00 UTC, kilinchange commented
另外，现在代码里写的都是中文注释，之前王老师提过尽量用英文注释，方便的话还是改一下吧。

2024-04-01 05:50 UTC, whjthu approved these changes

2024-04-01 05:53 UTC, whjthu approved these changes

2024-04-01 06:03 UTC, kilinchange approved these changes

2024-04-01 06:04 UTC, merged