add leakyRelu Op
InfiniTensor/InfiniTensor pull request #233
Opened 2024-06-06 09:05 UTC by baominghelly

# Description

We add a new Operator LeakyRelu in Cuda platform.

# Build && Test
1. build(Succeed): make install-python CUDA=ON 
```
Successfully built pyinfinitensor
Installing collected packages: pyinfinitensor
  Attempting uninstall: pyinfinitensor
    Found existing installation: pyinfinitensor 0.0.0
    Uninstalling pyinfinitensor-0.0.0:
      Successfully uninstalled pyinfinitensor-0.0.0
Successfully installed pyinfinitensor-0.0.0
```

2. unit test(Succeed): make test-onnx && make test-cpp. The failed test case isn't related to our change.
```

python3 pyinfinitensor/tests/test_onnx.py
import backend: <module 'backend' from '/home/libaoming/workplace/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-x86_64-linux-gnu.so'>
................................model: resnet18-v2-7.onnx(44.64 MiB)
..........................
----------------------------------------------------------------------
Ran 58 tests in 3.188s

OK

99% tests passed, 1 tests failed out of 74

Total Test time (real) =  37.77 sec

The following tests FAILED:
         64 - test_cuda_rope (Failed)
Errors while running CTest
```

3. integ test(Succeed): python test_infinitensor.py --model=./simple_cnn.onnx --device=CUDA
```
import backend: <module 'backend' from '/home/libaoming/workplace/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-x86_64-linux-gnu.so'>
arg setting:  Namespace(model='./simple_cnn.onnx', device='CUDA')

Model Name: simple
[1, 3, 32, 32]
The difference of results between ONNXRuntime and InfiniTensor looks good!
```

2024-06-07 08:49 UTC, bitzyz approved these changes

2024-06-07 08:50 UTC, bitzyz commented
可以尝试加一下half数据类型的试试

2024-06-17 02:32 UTC, whjthu requested changes

2024-06-17 02:32 UTC, whjthu commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +
额外空行删掉

2024-06-17 02:32 UTC, whjthu commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +
跟其他地方的格式保持一致

2024-06-17 02:32 UTC, whjthu commented on src/kernels/cuda/unary.cc
> +
额外空行

2024-06-17 02:32 UTC, whjthu commented on src/kernels/cuda/unary.cu
> +
额外空行

2024-06-17 02:32 UTC, whjthu commented on src/kernels/cuda/unary.cu
> +
额外空行

2024-06-17 02:32 UTC, whjthu commented on src/kernels/cuda/unary.cu
> +
额外空行

2024-06-17 02:32 UTC, whjthu commented on src/kernels/cuda/unary.cu
> +
额外空行

2024-06-19 06:32 UTC, baominghelly commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +
Done

2024-06-19 06:33 UTC, baominghelly commented on src/kernels/cuda/unary.cc
> +
Done

2024-06-19 06:33 UTC, baominghelly commented on src/kernels/cuda/unary.cu
> +
Done

2024-06-19 06:33 UTC, baominghelly commented on src/kernels/cuda/unary.cu
> +
Done

2024-06-19 06:33 UTC, baominghelly commented on src/kernels/cuda/unary.cu
> +
Done

2024-06-19 06:33 UTC, baominghelly commented on src/kernels/cuda/unary.cu
> +
Done

2024-06-24 00:01 UTC, whjthu approved these changes

2024-06-24 00:07 UTC, merged