add-elu-operator
InfiniTensor/InfiniTensor pull request #235
Opened 2024-06-13 08:29 UTC by zzhfz

Add a new Operator ELU in Cuda platform.

2024-06-14 09:07 UTC, bitzyz requested changes

2024-06-14 09:07 UTC, bitzyz commented on src/kernels/cuda/elu.cc
> +            size *= dims[i];
可以直接调用size()函数，在tensor.h中有

2024-06-14 09:07 UTC, bitzyz commented on src/kernels/cuda/elu.cu
> +        output[index] = (x >= 0) ? x : alpha * (exp(x) - 1);
float类型建议使用expf

2024-06-14 09:08 UTC, bitzyz commented
可以尝试一下支持其它的精度类型

2024-06-17 08:14 UTC, zzhfz commented on src/ffi/ffi_infinitensor.cc
> +    py::class_<GraphHandlerObj, std::shared_ptr<GraphHandlerObj>>(
当时编译有报错考虑使用 std::shared_ptr 解决，现在发现原代码可以成功编译了，已经改回：
```cpp
py::class_<Handler>(m, "GraphHandler")

2024-06-24 00:07 UTC, whjthu requested changes

2024-06-24 00:07 UTC, whjthu commented on pyinfinitensor/src/pyinfinitensor/onnx.py
这个文件发生了什么，为什么全部被改了

2024-06-24 00:07 UTC, whjthu commented on include/cuda/cuda_elu.h
elu 应该也是一个 unary？可以参考 leakyRelu 的写法，直接放到 unary 相关的文件里

2024-06-24 00:08 UTC, whjthu requested changes

2024-06-24 00:08 UTC, whjthu commented on include/core/graph_handler.h
> +    Tensor elu(Tensor input, Tensor output, float alpha);
参数名和其他保持一致，x 和 y

2024-06-24 02:43 UTC, bitzyz requested changes

2024-06-24 02:43 UTC, bitzyz commented on src/core/graph_handler.cc
> +        g->addOpWithOutputs<EluObj>(std::move(input), new_output, alpha);
这里为什么不直接使用addOp呢

2024-06-24 02:43 UTC, bitzyz commented on src/ffi/ffi_infinitensor.cc
> +             py::arg("alpha"))
.def("elu", &Handler::elu, policy::move)

2024-06-26 03:03 UTC, closed without merging