Accommodate avg pool1 d
InfiniTensor/InfiniTensor pull request #253
Opened 2024-08-15 05:40 UTC by Ziminli

Accommodated the existing pooling operation to accept 1D pooling. 
<img width="244" alt="image" src="https://github.com/user-attachments/assets/11fb8e1b-6372-4bcc-8306-ba8944ee333b">

2024-08-15 08:21 UTC, kilinchange commented on src/kernels/cuda/pooling.cc
> +            h = outDims[2] = 1;
这两行都拆开写吧，语义明确些

2024-08-15 09:54 UTC, kilinchange requested changes

2024-08-15 09:54 UTC, kilinchange commented on src/kernels/cuda/pooling.cc
> +        auto [n, c, h, w, kh, kw] = op->getNCHWRS();
这里不需要修改这几个值了吧，那还是 const 就行

2024-08-15 09:56 UTC, kilinchange approved these changes

2024-08-20 12:11 UTC, whjthu approved these changes

2024-08-20 12:11 UTC, merged