cnnl_scatterND：增加寒武纪的scatterND算子
InfiniTensor/InfiniTensor pull request #268
Opened 2024-12-24 07:56 UTC by xgqdut2016

<img width="932" alt="1735026975398" src="https://github.com/user-attachments/assets/3c062ce3-79e4-4acb-b14b-eda743b5163a" />

2025-01-24 09:25 UTC, kilinchange commented
请只保留前端修改，kernel 相关修改后续考虑直接接入统一算子库。

2025-02-05 02:35 UTC, kilinchange approved these changes

2025-02-05 07:06 UTC, bitzyz requested changes

2025-02-05 07:06 UTC, bitzyz commented on include/operators/scatterND.h
> +     * @param output The output tensor.
onnx文档中存在reduction这个属性，应该加上

2025-02-05 07:06 UTC, bitzyz commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                    tensors.get(node.output[0]),
同上，应该对reduction这个属性做判断处理

2025-02-05 07:06 UTC, bitzyz commented on src/operators/scatterND.cc
> +optional<vector<Shape>> ScatterNDObj::inferShape(const TensorVec &inputs) {
应该需要补充对indices、updates输入的形状检查

2025-02-05 09:23 UTC, bitzyz approved these changes

2025-02-05 09:48 UTC, kilinchange requested changes

2025-02-05 09:48 UTC, kilinchange commented on src/operators/scatterND.cc
> +      reduction(reduction) {
reduction 要 move

2025-02-05 09:48 UTC, kilinchange commented on src/core/graph_handler.cc
> +                                  std::move(updates), output, reduction)
reduction 要 move

2025-02-06 02:59 UTC, kilinchange approved these changes

2025-02-06 03:00 UTC, merged