cnnl_scatterElements：增加寒武纪平台的scatterElements算子
InfiniTensor/InfiniTensor pull request #269
Opened 2024-12-24 08:08 UTC by xgqdut2016

<img width="945" alt="1735027703170" src="https://github.com/user-attachments/assets/5f77ba80-c634-4c01-9d6f-044ba36df176" />

2025-01-24 09:25 UTC, kilinchange commented
请只保留前端修改，kernel 相关修改后续考虑直接接入统一算子库。

2025-02-05 03:26 UTC, kilinchange requested changes

2025-02-05 03:26 UTC, kilinchange commented on include/core/graph_handler.h
> +    Tensor scatterElements(Tensor data, Tensor indices, Tensor updates,
scatterElements 在 16 版本之后有 reduction 属性，若不支持请在注释里写明该算子支持的 onnx 版本范围

2025-02-05 07:11 UTC, bitzyz requested changes

2025-02-05 07:11 UTC, bitzyz commented on src/operators/scatterElements.cc
> +ScatterElementsObj::inferShape(const TensorVec &inputs) {
添加对data、updates、indices的形状防呆检查

2025-02-05 07:11 UTC, bitzyz commented on include/core/graph_handler.h
> +    Tensor scatterElements(Tensor data, Tensor indices, Tensor updates,
建议直接加上reduction这个属性，内部可以不做reduction，但应该预留

2025-02-05 09:25 UTC, bitzyz approved these changes

2025-02-05 09:46 UTC, kilinchange requested changes

2025-02-05 09:46 UTC, kilinchange commented on src/core/graph_handler.cc
> +                                        reduction)
这里和上面的 reduction 都加上 std::move 吧，减少一次拷贝。

2025-02-05 09:46 UTC, kilinchange commented on src/operators/scatterElements.cc
> +      reduction(reduction) {
这里也要 reduction(std::move(reduction))，避免一次拷贝

2025-02-06 03:01 UTC, kilinchange approved these changes

2025-02-06 05:39 UTC, closed without merging