Add CUDA Det and Proper Det Support
InfiniTensor/InfiniTensor pull request #273
Opened 2024-12-25 02:52 UTC by Ziminli

- Add the CUDA implementation of the Det operator
 - Add the necessary registration and tests for Det

2025-01-24 09:27 UTC, kilinchange commented
请只保留前端修改，kernel 相关修改后续考虑直接接入统一算子库。

2025-02-05 02:18 UTC, kilinchange requested changes

2025-02-05 02:18 UTC, kilinchange commented on src/operators/det.cc
> +DetObj::Mode DetObj::strToMode(const std::string &modeStr) const {
这个函数和 modeValue 似乎是一样的功能，为什么要写两份呢？

2025-02-05 02:18 UTC, kilinchange commented on test/kernels/cuda/test_cuda_det.cc
后端没加 kernel 这个测试应该不能跑吧

2025-02-05 06:03 UTC, bitzyz requested changes

2025-02-05 06:03 UTC, bitzyz commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                    "normal",
Det算子在onnx文档里没有mode这个属性，为什么还要保留呢

2025-02-05 06:03 UTC, bitzyz commented on src/ffi/ffi_infinitensor.cc
> +static std::string det_attr_of(Operator op) {
这个函数应该用不到吧，转onnx的话应该也不需要转mode这个属性

2025-02-05 07:36 UTC, kilinchange commented on src/operators/det.cc
> +DetObj::Mode DetObj::strToMode(const std::string &modeStr) const {
哦说错了，是 fromModeStr...

2025-02-05 07:51 UTC, Ziminli commented on src/operators/det.cc
> +DetObj::Mode DetObj::strToMode(const std::string &modeStr) const {
已删除多余函数

2025-02-05 08:11 UTC, Ziminli commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                    "normal",
因为原先寒武纪的实现里加了这个参数选项，然后我发现有模型有 log+Det 的这个组合，寒武纪 cnnl 库提供了这个选项，所以我推测这应该是当初寒武纪加了这个参数选项的原因，也就保留下来了。如果要严格按照 onnx 的定义的话，可以去除这个选项。

2025-02-05 09:06 UTC, Ziminli commented on src/ffi/ffi_infinitensor.cc
> +static std::string det_attr_of(Operator op) {
已移除

2025-02-05 09:06 UTC, Ziminli commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                    "normal",
已移除

2025-02-05 10:16 UTC, kilinchange approved these changes

2025-02-06 02:03 UTC, bitzyz approved these changes

2025-02-06 06:28 UTC, merged