Xpu
InfiniTensor/InfiniTensor pull request #82
Opened 2023-05-29 05:41 UTC by wanghailu0717

Support KUNLUN XPU

2023-08-22 07:44 UTC, wanghailu0717 commented
测试报告
```
[wanghailu@baidu Release]$ make test
Running tests...
Test project /home/wanghailu/InfiniTensor/build/Release
      Start  1: test_graph
 1/33 Test  #1: test_graph .......................   Passed    0.03 sec
      Start  2: test_graph_handler
 2/33 Test  #2: test_graph_handler ...............   Passed    0.04 sec
      Start  3: test_graph_replace
 3/33 Test  #3: test_graph_replace ...............   Passed    0.03 sec
      Start  4: test_hash
 4/33 Test  #4: test_hash ........................   Passed    0.02 sec
      Start  5: test_lazy_allocator
 5/33 Test  #5: test_lazy_allocator ..............   Passed    0.03 sec
      Start  6: test_search
 6/33 Test  #6: test_search ......................   Passed    5.13 sec
      Start  7: test_tensor_save
 7/33 Test  #7: test_tensor_save .................   Passed    0.03 sec
      Start  8: test_verify
 8/33 Test  #8: test_verify ......................   Passed    0.02 sec
      Start  9: test_batch_norm
 9/33 Test  #9: test_batch_norm ..................   Passed    0.02 sec
      Start 10: test_clip
10/33 Test #10: test_clip ........................   Passed    0.03 sec
      Start 11: test_concat
11/33 Test #11: test_concat ......................   Passed    0.02 sec
      Start 12: test_conv
12/33 Test #12: test_conv ........................   Passed    0.48 sec
      Start 13: test_conv_transposed_2d
13/33 Test #13: test_conv_transposed_2d ..........   Passed    0.02 sec
      Start 14: test_element_wise
14/33 Test #14: test_element_wise ................   Passed    0.02 sec
      Start 15: test_extend
15/33 Test #15: test_extend ......................   Passed    0.02 sec
      Start 16: test_gather
16/33 Test #16: test_gather ......................   Passed    0.02 sec
      Start 17: test_matmul
17/33 Test #17: test_matmul ......................   Passed    0.02 sec
      Start 18: test_pad
18/33 Test #18: test_pad .........................   Passed    0.02 sec
      Start 19: test_pooling
19/33 Test #19: test_pooling .....................   Passed    0.02 sec
      Start 20: test_reduce_mean
20/33 Test #20: test_reduce_mean .................   Passed    0.02 sec
      Start 21: test_reshape
21/33 Test #21: test_reshape .....................   Passed    0.02 sec
      Start 22: test_resize
22/33 Test #22: test_resize ......................   Passed    0.02 sec
      Start 23: test_slice
23/33 Test #23: test_slice .......................   Passed    0.02 sec
      Start 24: test_split
24/33 Test #24: test_split .......................   Passed    0.02 sec
      Start 25: test_transpose
25/33 Test #25: test_transpose ...................   Passed    0.02 sec
      Start 26: test_xpu_add
26/33 Test #26: test_xpu_add .....................   Passed    0.02 sec
      Start 27: test_xpu_concat
27/33 Test #27: test_xpu_concat ..................   Passed    0.02 sec
      Start 28: test_xpu_conv
28/33 Test #28: test_xpu_conv ....................   Passed    0.04 sec
      Start 29: test_xpu_matmul
29/33 Test #29: test_xpu_matmul ..................   Passed    0.02 sec
      Start 30: test_xpu_pooling
30/33 Test #30: test_xpu_pooling .................   Passed    0.02 sec
      Start 31: test_xpu_split
31/33 Test #31: test_xpu_split ...................   Passed    0.02 sec
      Start 32: test_xpu_transpose
32/33 Test #32: test_xpu_transpose ...............   Passed    0.02 sec
      Start 33: test_xpu_unary
33/33 Test #33: test_xpu_unary ...................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 33

Total Test time (real) =   6.35 sec
```

2023-09-01 02:17 UTC, PanZezhong1725 commented on test/kernels/xpu/test_xpu_add.cc
> +    EXPECT_TRUE(true);
这里是不是忘把注释改回去了？应该是 EXPECT_TRUE(outputCpu->equalData(outputGpu2Cpu)) 吧

2023-09-01 02:20 UTC, PanZezhong1725 commented on test/kernels/xpu/test_xpu_concat.cc
> +    EXPECT_TRUE(1);
提交的代码把print去掉，然后对比实际结果

2023-09-01 02:21 UTC, PanZezhong1725 commented on test/kernels/xpu/test_xpu_conv.cc
> +    EXPECT_TRUE(true);
同上

2023-09-06 01:15 UTC, whjthu requested changes

2023-09-06 01:15 UTC, whjthu commented on CMakeLists.txt
> +option(USE_XPU "Support KUNLUN MLU" ON)
是 KUNLUN XPU 不是 MLU
另外我在想直接叫 XPU 是不是也不合适，不止一款芯片叫 XPU

2023-09-06 01:15 UTC, whjthu commented on test/kernels/xpu/test_xpu_add.cc
> +    // CPU
不用的代码就直接删了吧

2023-09-06 01:15 UTC, whjthu commented on test/kernels/xpu/test_xpu_concat.cc
> +    EXPECT_TRUE(1);
这里也是没检查计算结果

2023-09-06 01:15 UTC, whjthu commented on test/kernels/xpu/test_xpu_pooling.cc
> +    EXPECT_TRUE(1);
没检查结果

2023-09-06 01:15 UTC, whjthu commented on test/kernels/xpu/test_xpu_split.cc
> +    EXPECT_TRUE(1);
没检查结果

2023-09-06 01:15 UTC, whjthu commented on test/kernels/xpu/test_xpu_transpose.cc
> +    EXPECT_TRUE(1);
没检查结果

2023-10-09 05:25 UTC, wanghailu0717 commented on test/kernels/xpu/test_xpu_concat.cc
> +    EXPECT_TRUE(1);
CPU Concat 算子缺失

2023-10-09 05:38 UTC, wanghailu0717 commented on test/kernels/xpu/test_xpu_add.cc
> +    // CPU
保留

2023-10-09 05:38 UTC, wanghailu0717 commented on test/kernels/xpu/test_xpu_concat.cc
> +    EXPECT_TRUE(1);
CPU Concat 算子缺失

2023-10-09 05:48 UTC, wanghailu0717 commented on test/kernels/xpu/test_xpu_split.cc
> +    EXPECT_TRUE(1);
CPU Split 算子缺失

2023-10-09 05:49 UTC, wanghailu0717 commented on test/kernels/xpu/test_xpu_transpose.cc
> +    EXPECT_TRUE(1);
CPU Transpose 算子缺失

2023-10-09 05:51 UTC, wanghailu0717 commented on CMakeLists.txt
> +option(USE_XPU "Support KUNLUN MLU" ON)
我看到已经变动为KUNLUN 了

2023-10-09 06:00 UTC, wanghailu0717 commented
2023.10.09 测试报告

```
Test project /home/wanghailu/new/InfiniTensor/build/Release
      Start  1: test_graph
 1/42 Test  #1: test_graph .......................   Passed    0.02 sec
      Start  2: test_graph_handler
 2/42 Test  #2: test_graph_handler ...............   Passed    0.02 sec
      Start  3: test_graph_replace
 3/42 Test  #3: test_graph_replace ...............   Passed    0.02 sec
      Start  4: test_hash
 4/42 Test  #4: test_hash ........................   Passed    0.02 sec
      Start  5: test_lazy_allocator
 5/42 Test  #5: test_lazy_allocator ..............   Passed    0.02 sec
      Start  6: test_search
 6/42 Test  #6: test_search ......................   Passed    4.66 sec
      Start  7: test_tensor_save
 7/42 Test  #7: test_tensor_save .................   Passed    0.02 sec
      Start  8: test_verify
 8/42 Test  #8: test_verify ......................   Passed    0.02 sec
      Start  9: test_all_gather
 9/42 Test  #9: test_all_gather ..................   Passed    0.02 sec
      Start 10: test_all_reduce
10/42 Test #10: test_all_reduce ..................   Passed    0.02 sec
      Start 11: test_batch_norm
11/42 Test #11: test_batch_norm ..................   Passed    0.02 sec
      Start 12: test_broadcast
12/42 Test #12: test_broadcast ...................   Passed    0.02 sec
      Start 13: test_clip
13/42 Test #13: test_clip ........................   Passed    0.02 sec
      Start 14: test_concat
14/42 Test #14: test_concat ......................   Passed    0.02 sec
      Start 15: test_conv
15/42 Test #15: test_conv ........................   Passed    0.23 sec
      Start 16: test_conv_transposed_2d
16/42 Test #16: test_conv_transposed_2d ..........   Passed    0.02 sec
      Start 17: test_element_wise
17/42 Test #17: test_element_wise ................   Passed    0.02 sec
      Start 18: test_expand
18/42 Test #18: test_expand ......................   Passed    0.02 sec
      Start 19: test_extend
19/42 Test #19: test_extend ......................   Passed    0.02 sec
      Start 20: test_gather
20/42 Test #20: test_gather ......................   Passed    0.02 sec
      Start 21: test_matmul
21/42 Test #21: test_matmul ......................   Passed    0.02 sec
      Start 22: test_pad
22/42 Test #22: test_pad .........................   Passed    0.02 sec
      Start 23: test_pooling
23/42 Test #23: test_pooling .....................   Passed    0.02 sec
      Start 24: test_reduce_mean
24/42 Test #24: test_reduce_mean .................   Passed    0.02 sec
      Start 25: test_reshape
25/42 Test #25: test_reshape .....................   Passed    0.02 sec
      Start 26: test_resize
26/42 Test #26: test_resize ......................   Passed    0.02 sec
      Start 27: test_slice
27/42 Test #27: test_slice .......................   Passed    0.02 sec
      Start 28: test_split
28/42 Test #28: test_split .......................   Passed    0.02 sec
      Start 29: test_transpose
29/42 Test #29: test_transpose ...................   Passed    0.02 sec
      Start 30: test_where
30/42 Test #30: test_where .......................   Passed    0.02 sec
      Start 31: test_xpu_add
31/42 Test #31: test_xpu_add .....................   Passed    0.02 sec
      Start 32: test_xpu_batch_norm
32/42 Test #32: test_xpu_batch_norm ..............   Passed    0.02 sec
      Start 33: test_xpu_concat
33/42 Test #33: test_xpu_concat ..................   Passed    0.02 sec
      Start 34: test_xpu_conv
34/42 Test #34: test_xpu_conv ....................   Passed    0.04 sec
      Start 35: test_xpu_conv_trans
35/42 Test #35: test_xpu_conv_trans ..............   Passed    0.02 sec
      Start 36: test_xpu_element_wise
36/42 Test #36: test_xpu_element_wise ............   Passed    0.02 sec
      Start 37: test_xpu_matmul
37/42 Test #37: test_xpu_matmul ..................   Passed    0.02 sec
      Start 38: test_xpu_pad
38/42 Test #38: test_xpu_pad .....................   Passed    0.02 sec
      Start 39: test_xpu_pooling
39/42 Test #39: test_xpu_pooling .................   Passed    0.02 sec
      Start 40: test_xpu_split
40/42 Test #40: test_xpu_split ...................   Passed    0.02 sec
      Start 41: test_xpu_transpose
41/42 Test #41: test_xpu_transpose ...............   Passed    0.02 sec
      Start 42: test_xpu_unary
42/42 Test #42: test_xpu_unary ...................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 42

Total Test time (real) =   5.76 sec
```

2023-10-12 07:48 UTC, whjthu requested changes

2023-10-12 07:48 UTC, whjthu commented on src/ffi/ffi_infinitensor.cc
> +        .FUNCTION(xpu_runtime)
kunlun_runtime

2023-10-12 07:48 UTC, whjthu commented on src/kernels/kunlun/batch_norm.cc
> +                BatchNormXdnn, "BatchNorm_xdnn_XPU_Float32");
KUNLUN_

2023-10-12 07:48 UTC, whjthu commented on src/kunlun/kunlun_runtime.cc
> +            printf(" op_time on xpu %lf\n", t);
kunlun xpu

2023-10-12 07:48 UTC, whjthu commented on src/kunlun/operator_timer.cc
> +double getPerfConvXPU(int n, int c, int h, int w, int f, int r, int s, int padh,
kunlun

2023-10-12 07:48 UTC, whjthu commented on src/kunlun/operator_timer.cc
> +    Runtime xpu = make_ref<KUNLUNRuntimeObj>();
kunlun

2023-10-16 01:53 UTC, whjthu approved these changes

2023-10-16 02:57 UTC, merged