框架支持bert/gpt2模型构图
InfiniTensor/InfiniTensor pull request #94
Opened 2023-07-13 09:02 UTC by bitzyz

框架支持bert/gpt2模型构图，主要工作如下：
1.添加了部分算子定义（where\expand\sqrt\erf）
2.对框架中的部分代码为了适配bert/gpt2模型做了改动，包含一些广播支持，默认属性参数设置，解除了一些限制较死的类型检查，其中存在一些hard coding，在commit相关信息中备注为hard coding

2023-08-17 08:49 UTC, constroy requested changes

2023-08-18 01:25 UTC, bitzyz commented on src/operators/gather.cc
> +    IT_ASSERT(index_dtype == DataType::UInt32 || index_dtype == DataType::Int64)
文档上面显示index是Int32或者Int64

2023-08-18 01:33 UTC, constroy commented on src/operators/gather.cc
> +    IT_ASSERT(index_dtype == DataType::UInt32 || index_dtype == DataType::Int64)
`Int32` 和 `UInt32` 是不能通用的。

2023-08-18 05:08 UTC, bitzyz commented on src/operators/gather.cc
> +    IT_ASSERT(index_dtype == DataType::UInt32 || index_dtype == DataType::Int64)
我以为你在强调input的datatype，这个uint32可以改一下

2023-08-21 04:32 UTC, YdrMaster approved these changes

2023-08-21 07:17 UTC, bitzyz commented on src/operators/gather.cc
> +    IT_ASSERT(index_dtype == DataType::UInt32 || index_dtype == DataType::Int64)
已修复

2023-08-29 08:06 UTC, constroy approved these changes

2023-08-29 08:06 UTC, merged