支持fp16 dtype
InfiniTensor/InfiniTensor pull request #96
Opened 2023-07-20 03:30 UTC by bitzyz

新增内容：
1.在框架内新增DataType::Float16对应ONNX中TensorProto::FLOAT16，并以uint8形式实现相应的数据copy
2.修改原有copyin中的防呆方法
3.为了测试resnet网络新增了flatten算子的onnx导出
4.由于调试中将chenjie和zhangyue的代码进行了微调，所以将其commit一并合入此commit中进行提交合入
测试：
1.本地以resnet模型为例，使用onnx自带的convert_fp16的功能将inputs转为fp16，测试模型的读入、构图、导出，均可以通过
2.搭建conv的单算子网络，设定输入为fp16类型，进行集成测试，可以顺利走到运行时成功调起kernel
3.在test_onnx.py文件中增加了conv fp16和flatten op的构图测试

2023-07-20 05:57 UTC, YdrMaster requested changes
好像还 format 了几个别的文件？不过我觉得问题不大

2023-07-20 05:57 UTC, YdrMaster commented on include/core/data_type.h
>      // legacy
这一行干掉吧，其实我原来这么放是想表示这俩序号不对

2023-07-20 05:57 UTC, YdrMaster commented on include/core/data_type.h
> +        sizeof(int8_t),   sizeof(uint8_t)};
这俩应该实际都是 `uint8_t` 存的？最好加个注释说明一下，过几天该忘了

2023-07-20 05:57 UTC, YdrMaster commented on include/core/data_type.h
> +        "int16_t", "int32_t",  "int64_t", "int8_t", "uint8_t"};
这个可以改名叫 `cpuType`，就是为了在 cpu 上正确存和访问的加的嘛

2023-07-20 05:57 UTC, YdrMaster commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                            list_int32_data.append(i.to_bytes(2, "little")[0])
这最好 `to_bytes` 一次……看这个函数这么多参数，说不定开销真不小

2023-07-21 02:42 UTC, bitzyz commented on include/core/data_type.h
>      // legacy
修复

2023-07-21 02:43 UTC, bitzyz commented on include/core/data_type.h
> +        sizeof(int8_t),   sizeof(uint8_t)};
已添加注释

2023-07-21 02:43 UTC, bitzyz commented on include/core/data_type.h
> +        "int16_t", "int32_t",  "int64_t", "int8_t", "uint8_t"};
已修改

2023-07-21 02:43 UTC, bitzyz commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                            list_int32_data.append(i.to_bytes(2, "little")[0])
已修改

2023-07-21 02:49 UTC, YdrMaster approved these changes
(*^_^*)

2023-07-21 03:30 UTC, whjthu requested changes

2023-07-21 03:30 UTC, whjthu commented on src/kernels/cuda/conv_half.cc
这个 kernel 好像没测试？另外现在命名不太统一，有的地方叫 half 有的地方叫 fp16。我思考下怎么叫比较合理。理论上说 bf16 也算是半精度的，但通常提到 half 特指 fp16 的比较多

2023-07-21 03:30 UTC, whjthu commented on src/ffi/ffi_infinitensor.cc
> +        .def("copyin_int8", &TensorObj::copyin<int8_t>, policy::move)
同一类型的 copyin 和 copyout 放到一起吧，另外为什么 int8 跟 uint8 只有 in 没有 out ？fp16 为什么没有对应的 copyin 和 copyout？

2023-07-21 03:30 UTC, whjthu commented on src/cuda/cuda_runtime.cc
> +        auto kernelAttrs = KernelAttrs{device, op->getOpType(), op->getDType()};
后面如果支持混合精度的情况的话 op->getDType() 可能是不够的，不过可以留着后面再做修改

2023-07-21 03:30 UTC, whjthu commented on include/core/data_type.h
> +    // <https://onnx.ai/onnx/intro/concepts.html#element-type>
我们现在好像搞了两套相同定义的类型系统，都与 onnx 的类型对齐，是不是可以考虑给合并一下？另一个在 graph_handler.h 里面，叫 OnnxDType

2023-07-21 03:30 UTC, whjthu commented on include/core/data_type.h
> +        sizeof(int8_t),   sizeof(uint8_t)};
这里实际上是会有两个类型大小，一个是中间存储状态的，比如 bool 或 int4 之类的在 CPU 端会用 int8 来存，但在实际推理过程中可能是按实际大小存的，现在这种写法可能后面会有问题。另外现在 fp16 也是按 uint8 存的吗？如果是的话这里把它的 size 设置成 1byte 是不是会对后面内存分配时候有影响？

2023-07-21 03:30 UTC, whjthu commented on src/core/operator.cc
>      auto dataType = inputs[0]->getDType();
inferDataType 直接按 inputs[0] 来写不会有问题吗？

2023-07-21 03:30 UTC, whjthu commented on src/kernels/cuda/conv_half.cc
> +        // TODO:
用不到的代码建议直接删掉，不要留大量代码注释在文件中，如果有些 todo 的部分可以写明后续需要添加的内容

2023-07-21 03:30 UTC, whjthu commented on src/kernels/cuda/conv_half.cc
> +        if (stat != CUDNN_STATUS_SUCCESS)
按之前说的 code format 单行也加上大括号

2023-07-21 03:30 UTC, whjthu commented on test/script/clang_format_inplace.sh
> +find ${PET_HOME}/src ${PET_HOME}/include ${PET_HOME}/test  -iname *.h -o -iname *.cc | xargs clang-format-14 -i
是不是跟 @YdrMaster 新写的格式化脚本重复了，以及这里竟然还遗留了 PET_HOME 这种名字。。

2023-07-21 04:27 UTC, YdrMaster commented on src/ffi/ffi_infinitensor.cc
> +        .def("copyin_int8", &TensorObj::copyin<int8_t>, policy::move)
fp16 cpu 里没有对应类型，现在是在前端里当作 `i8`/`u8` 处理的

2023-07-21 04:29 UTC, YdrMaster commented on include/core/data_type.h
> +    // <https://onnx.ai/onnx/intro/concepts.html#element-type>
呃，这个是 legacy 问题，这个 `DataType` 和 Onnx 对不上，要不就把这里的数改了，改成和 onnx 对的上的

2023-07-21 04:30 UTC, YdrMaster commented on test/script/clang_format_inplace.sh
> +find ${PET_HOME}/src ${PET_HOME}/include ${PET_HOME}/test  -iname *.h -o -iname *.cc | xargs clang-format-14 -i
这个文件在这个分支是临时改一下，和我那个一合并就删了，没事

2023-07-21 04:32 UTC, YdrMaster commented on include/core/data_type.h
> +        sizeof(int8_t),   sizeof(uint8_t)};
> 这里实际上是会有两个类型大小，一个是中间存储状态的，比如 bool 或 int4 之类的在 CPU 端会用 int8 来存，但在实际推理过程中可能是按实际大小存的，现在这种写法可能后面会有问题。另外现在 fp16 也是按 uint8 存的吗？如果是的话这里把它的 size 设置成 1byte 是不是会对后面内存分配时候有影响？

这个在算 bytes size 的时候三目单独拿出来讨论了，确实这么写不太好看，不知道怎么写好

2023-07-21 04:33 UTC, YdrMaster commented on src/kernels/cuda/conv_half.cc
我感觉就叫 `fp16` 比较好，历史已经证明了我知道 `int` 是 32 位还是要写 `int32_t`

2023-07-21 05:08 UTC, bitzyz commented on src/ffi/ffi_infinitensor.cc
> +        .def("copyin_int8", &TensorObj::copyin<int8_t>, policy::move)
copyout这块我看好像没有实际使用到，所以这块内容没有加上去。
fp16走的是u8的copyin

2023-07-21 05:10 UTC, bitzyz commented on src/cuda/cuda_runtime.cc
> +        auto kernelAttrs = KernelAttrs{device, op->getOpType(), op->getDType()};
是的，这个可能后面要改成传一个vec存op所有input的dtype，传到后端

2023-07-21 05:15 UTC, bitzyz commented on src/core/operator.cc
>      auto dataType = inputs[0]->getDType();
要不直接把这个operator基类的inferDataType置为空内容，具体函数内容下放到各个算子里去实现

2023-07-21 05:20 UTC, bitzyz commented on include/core/data_type.h
> +        sizeof(int8_t),   sizeof(uint8_t)};
这个主要原因是因为onnx中的TensorProto中有两个属性（int32_data\raw_data）可以存放FLOAT16对应的值，其中raw_data的是类型bytes，查看python文档，bytes可通过list转换为int8，因此是直接用uint8来存储float16类型的数值了，后面实际内存分配的时候是对他进行x2处理了

2023-07-21 09:20 UTC, kilinchange commented on include/core/data_type.h
> +        sizeof(int8_t),   sizeof(uint8_t)};
> > 这里实际上是会有两个类型大小，一个是中间存储状态的，比如 bool 或 int4 之类的在 CPU 端会用 int8 来存，但在实际推理过程中可能是按实际大小存的，现在这种写法可能后面会有问题。另外现在 fp16 也是按 uint8 存的吗？如果是的话这里把它的 size 设置成 1byte 是不是会对后面内存分配时候有影响？
> 
> 这个在算 bytes size 的时候三目单独拿出来讨论了，确实这么写不太好看，不知道怎么写好


在 onnx.py 里进行 copy_in 操作时，将 float 读出来的两个 uint8 进行加法（u8_0 * 256 + u8_1)，然后当成 uint16 传给 cpp 那边的接口，这样做就不需要在计算 bytes_size 时进行三目运算特判了，感觉会好一些？

2023-07-21 09:20 UTC, kilinchange commented on pyinfinitensor/src/pyinfinitensor/onnx.py
> +                        obj.copyin_uint8(list_int32_data)
这里可以通过 u8_0 * 256 + u8_1（具体 u8_0 和 u8_1 对应 element_byte 中的哪个元素得判断一下大端序小端序）来计算 FLOAT16 的 uint16 表示，用 uint16 来存储 FLOAT16，感觉会更加直观一些。

2023-08-02 08:34 UTC, whjthu approved these changes

2023-08-02 08:38 UTC, merged